- src/tree/mod.rs
- src/tree/test_treemath.rs
I pulled out `add_node` as the tree function used when adding people to an MLS group.
The test only calls the functions, there's nothing we can test here really. This should be used to generate test vectors though.
> Separate add_node

- src/codec.rs
- src/extensions.rs
- src/framing/mod.rs
- src/framing/sender.rs
- src/group/errors.rs
- src/group/mls_group/api.rs
- src/group/mls_group/apply_commit.rs
- src/group/mls_group/create_commit.rs
- src/group/mls_group/mod.rs
- src/group/mls_group/new_from_welcome.rs
- src/key_packages/test_key_packages.rs
- src/messages/proposals.rs
- tests/test_group.rs
`Sender` should not be used in the group API. This PR removes it from all public group APIs.
Make sure to review this with `Hide whitespace changes` enabled.
Fixes #20
> Remove Sender from Group API

- Cargo.toml
- src/ciphersuite/codec.rs
- src/ciphersuite/mod.rs
HPKE has these types now as well and we have to avoid confusing the types.
They should go away here, but we can only do that after the other open PRs are merged because it requires quite a number of changes.
> fix type confusion after hpke update

- CONTRIBUTING.md
A first version of engineering and contributing guidelines.
This is a basic set of guidelines of how to organise engineering work. Please let me know if you have any questions or remarks. We can iterate over this if we notice other things are important or some things don't make sense. I'm sure I also forgot some things.
Some things like PR templates we should put in GH once we moved to an org (I can't do it here).
> engineering and contributing guidelines

- src/framing/mod.rs
- src/group/mls_group/apply_commit.rs
- tests/test_group.rs
> globally rename 'confirmation' to 'confirmation_tag'

- benches/benchmark.rs
- src/extensions/life_time_extension.rs
- src/extensions/mod.rs
- src/extensions/test_extensions.rs
- src/key_packages/mod.rs
- src/key_packages/test_key_packages.rs
- src/tree/mod.rs
- src/tree/test_treemath.rs
- tests/test_framing.rs
- tests/test_group.rs
- tests/test_key_packages.rs
This PR works towards #32 by implementing the lifetime extension and making it mandatory in key packages.
The lifetime has basic tests in `test_extensions::lifetime` to check validity. This should be tested more in the context of key packages.
`KeyPackage.verify` now
* verifies that the signature on this key package is valid
* verifies that all mandatory extensions are present
* make sure that the lifetime is valid
There are tests in `generate_key_package` for this.
> Implement lifetime extension

- src/group/mls_group/api.rs
- src/group/mls_group/mod.rs
- tests/test_framing.rs
This PR changes the API so that it is not possible to create an application message and extract it as an MLSPlaintext.
> Change API to enforce always MLSCiphertext

- src/ciphersuite/mod.rs
- src/group/errors.rs
- src/group/managed_group.rs
- src/group/mls_group/apply_commit.rs
- src/group/mls_group/create_commit.rs
- src/key_packages/mod.rs
- src/messages/proposals.rs
- src/tree/mod.rs
- src/tree/node.rs
- src/tree/path_keys.rs
- src/tree/private_tree.rs
This is the first step towards getting rid of HPKE key definitions in the ciphersuite and #114 .
This removes the ability to clone HPKE private keys, which requires some changes to how state is moved around.
I didn't add any tests here but the paths are tests with the existing group tests and additional tests should be written for the ciphersuite and relevant paths later.
> Don't allow cloning private hpke keys

- Cargo.toml
- src/ciphersuite/mod.rs
- src/config.rs
- src/extensions/capabilities_extension.rs
- src/extensions/mod.rs
- src/extensions/test_extensions.rs
- tests/config.json
- tests/test_config.rs
This PR adds a global configuration to maelstrom (#85).
Pointing the `OPENMLS_CONFIG` environment variable to a JSON serialized config file (see `tests/config.json` for an example) sets the config used when running the library.
There are currently no tests for this, this needs a little additional infrastructure and isn't super high priority. The default case is tested.
> Global config

- benches/benchmark.rs
- src/ciphersuite/mod.rs
- src/config.rs
- src/creds.rs
- src/framing/test_framing.rs
- src/group/managed_group.rs
- src/group/mls_group/api.rs
- src/group/mls_group/create_commit.rs
- src/group/mls_group/mod.rs
- src/group/mls_group/new_from_welcome.rs
- src/key_packages/codec.rs
- src/key_packages/mod.rs
- src/key_packages/test_key_packages.rs
- src/messages/mod.rs
- src/messages/test_welcome.rs
- src/tree/mod.rs
- src/tree/test_treemath.rs
- tests/test_framing.rs
- tests/test_group.rs
- tests/test_key_packages.rs
There are two parts to this PR
Welcome messages cleanup and tests. This adds tests (`messages/test_welcome`) for welcome messages and makes the struct fields private.
Instead of passing around the entire ciphersuite (this should probably get a better name) we should usually use the ciphersuite name. This will make changing the ciphersuite easier.
> welcome messages & ciphersuite cleanup

- src/group/errors.rs
- src/group/mls_group/apply_commit.rs
- src/group/mls_group/create_commit.rs
- src/messages/mod.rs
- src/messages/proposals.rs
- src/tree/mod.rs
- src/tree/test_treemath.rs
This PR addresses the MLS protocol spec changes of how proposals are serialized inside Commits.
Additionally, there is some refactoring of how Commits are generated and processed:
- Apply Commit: check we have all proposals
- Create Commit: Filter proposals from current epoch
- Internal: get rid of membership changes
- Internal: Refactor how path_required is calculated 
- Internal: get rid keypackages in queued nodes
- Internal/API: error handling
- Documentation: more code is now documented
This PR does not have tests yet due to it's size. Tests will be included in a follow-up PR.
This PR also does not cover creating and processing new Proposal types like PSK & ReInit. This will be addressed in #76.
> Enable Commit to cover new proposal types

- .travis.yml
- Cargo.toml
* Moving to a dev version of evercrypt and hpke that support ARM.
* Adding ARM64 to CI (we don't have 32-bit arm unfortunately right now, but it should work as well)
> bump evercrypt and enable arm on travis

- src/framing/mod.rs
- src/group/mls_group/apply_commit.rs
- src/group/mls_group/create_commit.rs
- src/group/mls_group/mod.rs
- src/group/mls_group/new_from_welcome.rs
- src/messages/mod.rs
- src/messages/test_welcome.rs
This PR addresses a spec change and removes the `interim_transcript_hash` from `GroupInfo`.
> Remove interim_transcript_hash from GroupInfo

- Cargo.toml
- src/ciphersuite/codec.rs
- src/ciphersuite/mod.rs
- src/creds.rs
- src/group/mls_group/create_commit.rs
- src/key_packages/codec.rs
- src/key_packages/mod.rs
- src/key_packages/test_key_packages.rs
- src/messages/test_welcome.rs
- src/tree/mod.rs
- src/tree/private_tree.rs
- src/tree/test_path_keys.rs
- src/tree/test_private_tree.rs
* Remove hpke keys from ciphersuite and use keys provided by the hpke crate.
* Use a global HPKE instance in the ciphersuite.
This works towards cleaning up the ciphersuite #114 .
Replacing #124
> use hpke keys

- src/framing/mod.rs
- src/group/managed_group.rs
- src/group/mls_group/apply_commit.rs
- src/group/mls_group/create_commit.rs
- src/group/mls_group/mod.rs
If #122 is meant only for the `Api` trait, then it's a no-op. In this PR, I have changed some of the `MlsGroup` implementation function names, as `MlsGroup` also implements the `Api`.
Fixes #122 (I think).
Naming Guidlines: https://rust-lang.github.io/api-guidelines/naming.html
> Change Api function names for compliance with the Naming Guidelines

- .github/workflows/main.yml
- fuzz/.gitignore
- fuzz/Cargo.toml
- fuzz/fuzz_targets/decode_key_package_target.rs
- fuzz/fuzz_targets/welcome_fuzz_decode_target.rs
- src/ciphersuite/ciphersuites.rs
- src/ciphersuite/codec.rs
- src/ciphersuite/mod.rs
- src/codec.rs
- src/errors.rs
This PR adds the basic infrastructure for fuzzing in #154.
I'm skipping the GH action for spot fuzzing for now, the setup is a little weird. I'll add that later.
The key package fuzzer will quickly fail. This will need more work as sketched in the changes to ciphersuite already.
> init fuzzing infrastructure

- src/group/managed_group.rs
- src/group/mls_group/mod.rs
- src/group/mls_group/new_from_welcome.rs
- src/tree/index.rs
- src/tree/mod.rs
This PR aims to reduce some of the conversions from `LeafIndex` to `NodeIndex` by implementing `Index` and `MutIndex`, so we can index `Vec<Node>` directly with `LeafIndex` without an explicit detour via `NodeIndex`
> Some leaf index refactoring

- benches/benchmark.rs
- src/ciphersuite/mod.rs
- src/ciphersuite/signable.rs
- src/creds.rs
- src/framing/mod.rs
- src/framing/test_framing.rs
- src/group/mls_group/api.rs
- src/group/mls_group/create_commit.rs
- src/group/mls_group/mod.rs
- src/key_packages/mod.rs
- src/key_packages/test_key_packages.rs
- src/tree/mod.rs
- src/tree/test_treemath.rs
- tests/test_framing.rs
- tests/test_group.rs
- tests/test_key_packages.rs
This PR cleans up the API a little by getting rid of Identity and introducing `CredentialBundle`, which, analogous to `KeyPackageBundle`, contains a `Credential` and the corresponding `PrivateSignatureKey`.
> Remove Identity in favor of CredentialBundle

- Cargo.toml
- src/ciphersuite/mod.rs
- src/ciphersuite/test_ciphersuite.rs
- src/key_packages/mod.rs
- src/tree/mod.rs
- src/tree/private_tree.rs
HPKE 0.0.2 is almost there. Moving to the new version here already to unblock #129 .
* also adds a basic hpke seal test, there should be more of this
* The `as_slice` function of `HPKEPrivateKey` is behind the `hazmat` feature. We should try to get rid of this.
> bump hpke and evercrypt version

- src/ciphersuite/codec.rs
- src/ciphersuite/mod.rs
- src/ciphersuite/test_ciphersuite.rs
- src/creds.rs
- src/framing/test_framing.rs
- src/group/mls_group/create_commit.rs
- tests/test_key_packages.rs
Move sign and verify into the signature keys.
Note that this requires cloning the ciphersuite into the keys for now. This should be changed later by using a global ciphersuite from the config or borrowing the existing cihpersuite.
> ciphersuites cleanup: Signature keys

- src/ciphersuite/test_ciphersuite.rs
- src/messages/test_welcome.rs
The HPKE 0.0.2 branch has a fix for #172 and some more goodness. But this is needed now to unbreak maelstrom.
> adapt to HPKE changes

- src/extensions/mod.rs
- src/extensions/parent_hash_extension.rs
- src/group/managed_group.rs
- src/group/mls_group/apply_commit.rs
- src/group/mls_group/create_commit.rs
- src/group/mls_group/mod.rs
- src/group/mls_group/new_from_welcome.rs
- src/key_packages/mod.rs
- src/lib.rs
- src/tree/mod.rs
- src/tree/node.rs
- src/utils.rs
- src/validator.rs
- tests/test_group.rs
- tests/test_key_packages.rs
* Remove a couple `get_` in names.
* Don't copy the tree every time with `public_key_tree`.
> misc cleanup naming

- .travis.yml
Since Travis Ci became so slow and unreliable and we only need it for ARM, I removed all other targets. Maybe this helps staying within the 1000 minutes they allow fro OS projects as of now (see #189).
> Only keep ARM on linux for Travis CI

- README.md
- benches/benchmark.rs
- src/ciphersuite/test_ciphersuite.rs
- src/framing/test_framing.rs
- src/key_packages/test_key_packages.rs
- src/prelude.rs
- src/tree/test_private_tree.rs
- src/tree/test_secret_tree.rs
- src/tree/test_treemath.rs
- tests/test_framing.rs
- tests/test_group.rs
This is a follow-up PR to #177.
This PR re-enables all remaining group operation tests that were previously commented out and closes #77.
While much more testing will be needed to cover more scenarios, this is not in the scope of this PR. The only goal is to have a baseline for testing.
> Re-enable group tests 3/3

- .github/workflows/main.yml
- Cargo.toml
Looks like the CI cache is broken (probably because of the way the dependencies work right now). Let's disable for now until we move to more stable dependencies.
> Don't cache on CI

- src/framing/sender.rs
- src/group/managed_group/mod.rs
- src/group/mls_group/apply_commit.rs
- src/key_packages/mod.rs
- src/prelude.rs
- src/tree/mod.rs
- tests/test_managed_group.rs
This PR adds a first integration test for the managed group API that is modeled after the integration test for `MlsGroup`.
The test is expected to fail because of the missing implementation.
The purpose of this PR is to refine the API in some places before starting to implement it.
> Integration test for managed group API

- src/framing/mod.rs
- src/group/mls_group/apply_commit.rs
- src/group/mls_group/create_commit.rs
- src/group/mls_group/mod.rs
- src/group/mls_group/new_from_welcome.rs
- src/schedule/errors.rs
- src/schedule/mod.rs
- src/schedule/test_schedule.rs
- src/tree/secret_tree.rs
- src/tree/test_secret_tree.rs
Fixes #91 by introducing a dedicated function to retrieve the `encryption_secret` from an `EpochSecrets` object. The function removes the `Secret` such that ownership can be passed to the `SecretTree` constructor, at the end of which the Secret is dropped.
> Improve FS by dropping the encryption_secret after use

- src/codec.rs
- src/framing/mod.rs
- src/group/mls_group/apply_commit.rs
- src/group/mls_group/create_commit.rs
- src/group/mls_group/new_from_welcome.rs
- src/messages/codec.rs
- src/messages/mod.rs
- src/schedule/mod.rs
- src/schedule/psk.rs
- src/tree/mod.rs
- tests/test_group.rs
- tests/utils/mod.rs
As part of #83 (error handling) I did a little cleanup of the messages module.
This PR
* adds PSK dummy structs to the schedule and adds them to the `GroupSecrets` .
* moves codec implementations out of the main messages module file.
* messages only return `CodecErrors`.
> messages refactoring

- src/framing/errors.rs
- src/framing/mod.rs
- src/framing/test_framing.rs
- src/group/managed_group/mod.rs
- src/group/mls_group/mod.rs
- src/key_packages/mod.rs
- src/prelude.rs
- src/tree/mod.rs
- src/tree/sender_ratchet.rs
- tests/test_managed_group.rs
This PR introduces a quick fix for handshake message encryption. It also fixes a missing `KeyPackageBundle` signature in Managed Groups.
Note that this fix just enables HS encryption for now, it does not address #243.
> Quick fix for handshake message encryption

- cli/src/backend.rs
- src/group/mls_group/apply_commit.rs
- src/group/mls_group/create_commit.rs
- src/tree/mod.rs
- src/tree/test_resolution.rs
This PR fixes #148.
The `resolve()` function is modified so that it accepts an exclusion list of `NodeIndex`es to filter out from the resolution.
The exclusion list is created in `apply_proposal()` when new members are added to a provisional tree and passed to the `resolve()` function.
There is a test to verify that the filtering works.
> Redundant ciphertexts

- src/group/managed_group/mod.rs
- tests/test_managed_group.rs
This PR fixes #263.
There was a bug in the managed API where potential add proposals in the pending proposals queue could be applied without the API returning a corresponding `Welcome` message for the new joiners to consume. This has been fixed.
This is mostly covered by existing tests for creating `Commit` messages, but a negative was added to the integration test for the managed API.
> Return optional Welcome messages

- Cargo.toml
There are a couple fixes in HPKE and evercrypt.
This should also build on Windows (it's not under CI yet, so no guarantees).
replacing #260
> Bump HPKE and evercrypt

- src/ciphersuite/errors.rs
- src/ciphersuite/mod.rs
- src/ciphersuite/signable.rs
- src/codec/errors.rs
- src/codec/mod.rs
- src/config/errors.rs
- src/credentials/errors.rs
- src/credentials/mod.rs
- src/error.rs
- src/extensions/errors.rs
- src/extensions/mod.rs
- src/framing/mod.rs
- src/framing/test_framing.rs
- src/group/errors.rs
- src/group/managed_group/callbacks.rs
- src/group/managed_group/mod.rs
- src/group/mls_group/create_commit.rs
- src/group/mls_group/mod.rs
- src/group/mls_group/new_from_welcome.rs
- src/key_packages/errors.rs
- src/key_packages/mod.rs
- src/lib.rs
- src/messages/errors.rs
- src/messages/test_proposals.rs
- src/prelude.rs
- src/tree/errors.rs
- src/tree/mod.rs
- src/tree/test_private_tree.rs
- src/tree/test_treemath.rs
This PR finishes the error rewrite. It also introduces a new type of errors.
Now the following is allowed as well.
```Rust
implement_error! {
pub enum CredentialError {
Simple {
UnsupportedCredentialType = "Unsupported credential type",
}
Complex {
ConfigError(ConfigError) = "See `ConfigError` for details.",
CryptoError(CryptoError) = "See `CryptoError` for details.",
}
}
}
```
fixes #83
> finish error rewrite

- src/group/managed_group/errors.rs
- src/group/managed_group/mod.rs
- src/group/managed_group/test_managed_group.rs
- tests/test_managed_group.rs
What it says on the title, plus a test.
This was originally committed as part of
280a81eab31608de537683a9aa7370d06945e5a4 by @raphaelrobert.
> Throw an error when trying to add or remove members with an empty input

- src/tree/hashes.rs
- src/tree/mod.rs
This is a small follow-up PR to #293.
It moves all functions related parent & tree hashes to `hashes.rs`. I didn't do this earlier, so that it wouldn't impair reviews.
No code is changed in this PR.
> Move tree hashing code

- Cargo.toml
- test_macros/Cargo.toml
- test_macros/src/lib.rs
- tests/test_key_packages.rs
This PR adds a new crate `test_macros` that exposes a proc-macro
`ctest` that allows defining tests for all supported ciphersuites
as follows
```
ctest!(test_name {
// test body
})
```
This is used to replace the existing tests in tests/test-key_packages.rs
> Proc macro to test all ciphersuites

- Cargo.toml
- tls-codec-derive/Cargo.toml
- tls-codec-derive/src/lib.rs
- tls-codec-derive/tests/decode.rs
- tls-codec-derive/tests/encode.rs
- tls-codec/Cargo.toml
- tls-codec/src/arrays.rs
- tls-codec/src/hpke.rs
- tls-codec/src/lib.rs
- tls-codec/src/primitives.rs
- tls-codec/src/tls_vec.rs
- tls-codec/tests/decode.rs
- tls-codec/tests/encode.rs
This PR implements the TLS codec in a separate crate as well as corresponding derive macros for serialization and de-serialization.
This will allow us to remove (almost) all `Codec` related code. I'll do so in follow ups.
> TLS codec crate & derive

- test_macros/src/lib.rs
Adds a macro that allows indicating that we expect a test to fail when using the ciphersuite proc macros.
I built this for the interop test scenario PR, but ended up not using it. It might be useful for the future, though.
> Add ctest_panic macro

- src/ciphersuite/mod.rs
- src/ciphersuite/signable.rs
- src/ciphersuite/test_ciphersuite.rs
- src/credentials/errors.rs
- src/credentials/mod.rs
- src/framing/errors.rs
- src/framing/plaintext.rs
- src/group/errors.rs
- src/group/mls_group/new_from_welcome.rs
- src/key_packages/mod.rs
- src/tree/hashes.rs
- src/tree/mod.rs
- src/tree/test_hashes.rs
Fixes #297. Follow-up to #293.
Some of the return values of verification functions were still `bool`. Now the return types are consistently `Result<(), Error>`.
> Make results of sign/verify consistent

- src/group/mls_group/new_from_welcome.rs
- src/schedule/mod.rs
- src/tree/mod.rs
- src/tree/secret_tree.rs
- src/tree/test_treemath.rs
- src/tree/treemath.rs
Fixes #96.
I cleaned up the direct path mess in `treemath`. Now there are only two functions, depending on whether the direct path starts from a leaf or an intermediary node. Adds some type safety as well, because `LeafIndex` is used more often now.
> Consolidate direct_path functions in TreeMath

- src/credentials/mod.rs
- src/key_packages/errors.rs
- src/key_packages/mod.rs
- src/key_packages/test_key_packages.rs
Fixes #294 and re-enables the key package unit tests that seem to have been de-activated for a while.
> KeyPackage constructor check for mismatch

- src/group/managed_group/callbacks.rs
- src/group/managed_group/mod.rs
- src/group/managed_group/test_managed_group.rs
This PR fixes #329 by passing the correct sender to the event dispatcher and additionally fixes the wrong order of leaver and remover in the callback.
A small step in code change, a huge leap in testing.
> Fix remover bug

- .github/workflows/tests.yml
- Cargo.toml
- src/ciphersuite/mod.rs
- src/framing/ciphertext.rs
- src/group/errors.rs
- src/group/mls_group/apply_commit.rs
- src/group/mls_group/create_commit.rs
- src/group/mls_group/mod.rs
- src/group/mls_group/new_from_welcome.rs
- src/group/mls_group/test_mls_group.rs
- src/group/mod.rs
- src/schedule/errors.rs
- src/schedule/mod.rs
- src/tree/kat_encryption.rs
- src/tree/kat_treemath.rs
- src/tree/mod.rs
- src/tree/private_tree.rs
- src/tree/secret_tree.rs
- src/utils.rs
In preparation for the key schedule test vectors I re-organized the
key schedule and moved the logic into the actual key schedule module
instead of the group.
There are no changes to functionality PR, only moving code around.
This PR also removes the test-vector feature as it is no longer needed.
> key schedule reorg

- src/schedule/psk.rs
There was a missing line break in a comment that threw off the doc tests.
Probably another reason to deactivate comment formatting for now (see #351).
> Fix doc tests

- rustfmt.toml
- src/group/managed_group/mod.rs
- src/group/managed_group/resumption.rs
- src/group/mls_group/mod.rs
- src/schedule/psk.rs
Since we have too many unrelated changes due to comment formatting I removed the rule for now. Hopefully this will be in stable at some point and then we can re-enable it.
> Reformat comments one last time and remove formatting rule

- README.md
In the light of #364 we should make clear what's the minimum rustc version is OpenMLS requires.
> Add rustc minimum version to readme

- Cargo.toml
- tls-codec/Cargo.toml
Fixes #246.
The fix in `evercrypt-rust` should make it easier to build OpenMLS on Windows.
> Fix Windows build

- .github/codecov.yml
- .github/workflows/coverage.yml
- Cargo.toml
- codecov.yml
- src/config/mod.rs
- src/extensions/test_extensions.rs
- src/group/managed_group/test_managed_group.rs
- src/group/mls_group/test_duplicate_extension.rs
- src/group/mls_group/test_mls_group.rs
- src/lib.rs
- src/test_util/mod.rs
- test_macros/Cargo.toml
- test_macros/src/lib.rs
- test_macros/tests/tests.rs
- tests/test_decryption_key_index.rs
- tests/test_interop_scenarios.rs
- tests/test_key_packages.rs
- tests/utils/mod.rs
This includes the Code from #328 and changes the test proc macro. 
This still requires nightly (when merging I’ll file a follow up to use stable again once it’s released). The linking issue came from a cyclic dependency between the test macro and the main lib. While this is fine for the compiler tarpaulin appears to have issues with it. And since it’s not great in general I rewrote it a little. It’s not as seem less now but therefore more flexible and it fixes the codecov issues.
> test macro and codecov fix

- src/ciphersuite/mod.rs
- src/framing/ciphertext.rs
- src/group/managed_group/mod.rs
- src/group/mls_group/apply_commit.rs
- src/group/mls_group/create_commit.rs
- src/group/mls_group/mod.rs
- src/group/mls_group/new_from_welcome.rs
- src/group/tests/kat_transcripts.rs
- src/messages/mod.rs
- src/schedule/mod.rs
- src/tree/tests/kat_encryption.rs
- src/utils.rs
After looking at dependencies between the modules I started cleaning up the ciphersuite and key schedule. There are a couple more things that could be done here but this would require having something like a `trait Secret`.
Similar cleanups are needed for the other modules as well.
> ciphersuite secret cleanup

- src/group/managed_group/errors.rs
- src/group/managed_group/mod.rs
- src/group/managed_group/ser.rs
- src/group/managed_group/test_managed_group.rs
- src/key_store/errors.rs
- src/key_store/mod.rs
- src/key_store/test_key_store.rs
- src/lib.rs
- src/prelude.rs
- tests/test_decryption_key_index.rs
- tests/test_interop_scenarios.rs
- tests/test_managed_api.rs
- tests/test_managed_group.rs
- tests/utils/managed_utils/client.rs
- tests/utils/managed_utils/mod.rs
This PR replaces #334, as it goes a step further and doesn't keep the KeyStore reference in the ManagedGroup struct, but instead passes a KeyStore reference into every call into the Managed Group API. This allows us to avoid lifetime issues, as Rust doesn't allow struct-internal references.
One caveat in this PR that might be worth discussing:
* We currently ignore (i.e. `unwrap`) PoisonErrors when accessing KeyPackageBundles and CredentialBundles. The argument being that there is (to my knowledge) no way that the code can panic while it holds a write lock. In particular while holding a write lock, we only interact with the HashMap using `get`, `insert` or `remove`, which should be safe.
The PR is rather large, but should be easy to review, as a lot of the changes are due to the change of …
> Change the Managed Group to accept a KeyStore ref instead of keeping a CredentialBundle ref

- src/error.rs
Error descriptions could not be accessed from outside the crate.
> Fix error description visibility

- src/key_packages/codec.rs
- src/key_packages/errors.rs
- src/key_packages/mod.rs
Encoding of key packages is a performance bottleneck.
In order to speed up things like tree hashes this PR
serializes the key package on creation and every update
and stores the serialized value in the key package itself.
> Store encoded key_pacakge

- src/ciphersuite/codec.rs
- src/codec/mod.rs
- src/key_packages/codec.rs
- src/tree/codec.rs
- src/tree/hashes.rs
- tls-codec-derive/src/lib.rs
- tls-codec/src/arrays.rs
- tls-codec/src/hpke.rs
- tls-codec/src/lib.rs
- tls-codec/src/primitives.rs
- tls-codec/src/tls_vec.rs
This PR starts using the tls-codec for OpenMLS TLS encoding, starting
with the tree hash structs. Note that this is a mix now, but the tree
hash inputs are pretty self contained and therefore a good starting
point. Some of the encoding is a little more manual than before. This
should be improved later on when more structs use the tls-codec crate.
The tls-codec crate now offers a way to pre-allocate memory for
serializing. The `TlsSize` trait must be implemented for any struct
that want to implement `Serialize` and provides a `serialized_len`
method to get the length of the struct before serializing.
This reduces the tree_hash time by about 30%. There's a lot more to
do here, but this is an easy start to improve performance.
> use tls-codec for tree hash structs

- src/framing/plaintext.rs
- src/group/managed_group/errors.rs
- src/group/managed_group/events.rs
- src/group/managed_group/mod.rs
- src/group/managed_group/test_managed_group.rs
- tests/test_managed_group.rs
- tests/utils/managed_utils/client.rs
- tests/utils/managed_utils/mod.rs
This PR refactors the functions in the Managed API to accept individual messages (`process_message`) and return individual messages (`propose_...`, etc).
This necessitates some refactoring of the events returned and in particular allows us to return errors if messages are invalid as opposed to just putting error events into the queue.
> Refactor Managed API to accept and return individual messages

- src/group/managed_group/config.rs
- src/group/managed_group/mod.rs
- src/group/managed_group/test_managed_group.rs
- src/key_store/mod.rs
- tests/test_decryption_key_index.rs
- tests/test_interop_scenarios.rs
- tests/test_managed_api.rs
- tests/test_managed_group.rs
- tests/test_tree_kem_kat.rs
This PR adds the ratchet tree extension to the  `ManagedGroup` config and adds an integration test.
This is likely to be rewritten once we tackle extension for good, but for now it just aligns `ManagedGroup` with `MlsGroup` in that regard.
> Add ratchet tree extension to managed group

- openmls/src/schedule/mod.rs
Fixes #421.
We don't have the notion of an explicit "add only" commit. The mechanics are there, though. So on the level of the MLS Group API, one can not have any remove/update propsals and don't flip the "force self update" bit, which will result in an "add only"/"partial" commit.
> Rename add only commit to partial commit

- cli/README.md
- cli/src/user.rs
This PR makes the CLI client use RatchetTreeExtensions and fixes a small bug that causes a borrow-checker panic at runtime.
> Enable RatchetTreeExtensions in the CLI client

- openmls/src/ciphersuite/signature.rs
- openmls/src/credentials/mod.rs
- openmls/src/credentials/tests.rs
This PR adds a function to `CredentialBundle` to create it from existing keys. This feature was requested by OpenMLS users.
> Create CredentialBundle from existing keys

- openmls/src/framing/ciphertext.rs
- openmls/src/framing/codec.rs
- openmls/src/framing/message.rs
- openmls/src/framing/plaintext.rs
- openmls/src/framing/validation.rs
- openmls/src/group/managed_group/errors.rs
- openmls/src/group/managed_group/validation.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/group/tests/mod.rs
- openmls/src/group/tests/test_validation.rs
This PR starts the validation testing. The tests are named after the semantic validation checks as outlined in the [wiki](https://github.com/openmls/openmls/wiki/Message-validation). This works towards #133.
This PR only contains 2 tests so far. If we agree on the structure I'll follow up with more tests.
> Start validation tests

- rust_crypto/src/lib.rs
Fixes a deprecated API call when creating a signature from bytes.
> Fix deprecated API call in RustCrypto

- rust_crypto/src/lib.rs
The given decryption implementations for AEAD in `rust_crypto` for the cases `ChaCha20Poly1305` and `Aes256Gcm` did not use the regarding decryption but encryption methods of `aes-gcm`. I assume this bug was introduced by copy / paste, this PR should fix it :+1:
> Correct decryption methods for AEAD

- openmls/Cargo.toml
- openmls/src/ciphersuite/signature.rs
With a feature flag on top I'm fine with this for now.
Ideally all the signature key structs move out of the main library. But that's a bigger effort. Then the crypto backends could handle this whatever way they liked.
> crypto-subtle feature

- openmls/src/framing/codec.rs
- openmls/src/framing/message.rs
- openmls/src/framing/plaintext.rs
- openmls/src/framing/validation.rs
- openmls/src/group/managed_group/application.rs
- openmls/src/group/managed_group/mod.rs
- openmls/src/messages/public_group_state.rs
- openmls/src/schedule/errors.rs
- openmls/src/schedule/mod.rs
This PR fixes new clippy warning introduced in v1.57. 
It also fixes #585, because it just meant lifting the test-only visibility of the conversion.
The main change is that `MlsMessageIn/Out` now use `Box`, which makes sense, since they are likely to be used in a `Vec` anyway.
> New Rust version, new clippy warnings

- interop_client/Cargo.toml
- interop_client/src/main.rs
This PR fixes the interop client. `clap` v3 is not stable yet and a breaking change was recently introduced that broke the CI. It looks like the current version of `clap` is the RC, so hopefully this won't happen anymore.
> Fix interop client

- interop_client/src/main.rs
- openmls/Cargo.toml
- openmls/benches/benchmark.rs
- openmls/src/ciphersuite/aead.rs
- openmls/src/ciphersuite/tests/test_ciphersuite.rs
- openmls/src/schedule/kat_key_schedule.rs
- openmls/src/tree/tests_and_kats/unit_tests/test_hashes.rs
- openmls/src/tree/tests_and_kats/unit_tests/test_private_tree.rs
- openmls/src/tree/tests_and_kats/unit_tests/test_resolution.rs
- openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
- openmls/src/tree/tests_and_kats/unit_tests/test_sender_ratchet.rs
- openmls/src/tree/tests_and_kats/unit_tests/test_tree_truncation.rs
- openmls/src/tree/tests_and_kats/unit_tests/test_treemath.rs
This PR follows up on #600 and adds `rstests` to the tests that were missed initially.
For testing purposes, it also adds `evercrypt` to the benchmarks.
Note: Changes in indentation blow up the size of this PR again. No code was changed except for adjusting to `rstests`.
> Follow-up for #600

- openmls/src/framing/plaintext.rs
- openmls/src/framing/sender.rs
- openmls/src/group/mls_group/create_commit.rs
- openmls/src/group/mls_group/create_commit_params.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/proposals.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/group/mls_group/test_proposals.rs
- openmls/src/group/mls_group/validation.rs
- openmls/src/group/tests/kat_transcripts.rs
- openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
This PR allows the creation of Commits, MlsPlaintexts and Proposals with a `SenderType` other than `Member`. This is in preparation of the external init feature.
> Sender and Commit Types

- openmls/src/framing/codec.rs
At this point the sender type is always member. This will change in future though.
But the context should only be present for members.
That's why we just assert this here.
Fixes #477
> Assert that only members add a context to MlsPlaintextTBS

- openmls/src/group/mls_group/mod.rs
Fixes #387. This is a left-over from the tree rewrite that I thought had more implications than it actually does.
> Avoid clone in credential-getter of MlsGroup

- openmls/src/treesync/diff.rs
- openmls/src/treesync/tests_and_kats.rs
- openmls/src/treesync/tests_and_kats/tests.rs
- openmls/src/treesync/tests_and_kats/tests/test_diff.rs
This fixes the bug found by @franziskuskiefer in the process of reviewing #634, where instead of adding a leaf in the first blank position, it instead adds it in the last. The test is very minimal and only tests the exact conditions under which the bug occurs. More expansive tests and proper test utils will be added in the course of #625 and #624.
> Fix bug in free leaf computation and add simple test

- openmls/Cargo.toml
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/test_utils/test_framework/client.rs
- openmls/src/test_utils/test_framework/mod.rs
- openmls/tests/test_decryption_key_index.rs
- openmls/tests/test_interop_scenarios.rs
- openmls/tests/test_managed_api.rs
This PR replaces the `RefCell`s from the tests by a `RwLock` and parallelizes the testing framework.
After this, we can address #108 more easily.
The speedup is roughly 2x for all tests on my 8+2 core machine (the CI will probably not see such a sharp decrease).
> Remove RefCells in testing & parallelize testing framework

- cli/src/user.rs
- delivery-service/ds/src/test.rs
- interop_client/src/main.rs
- openmls/src/framing/ciphertext.rs
- openmls/src/framing/test_framing.rs
- openmls/src/framing/validation.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/process.rs
- openmls/src/group/mls_group/config.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/prelude.rs
- openmls/src/tree/mod.rs
- openmls/src/tree/secret_tree.rs
- openmls/src/tree/sender_ratchet.rs
- openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
- openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
- openmls/src/tree/tests_and_kats/unit_tests/test_sender_ratchet.rs
- openmls/tests/test_group.rs
This PR introduces a configuration for sender ratchet parameters:
- The parameters can be set with `SenderRatcherConfiguration` in `MlsGroupConfig`
- The default values will be more conservative once #265 and #243 are addressed
- The unit tests now better cover the sender ratchet
Fixes #457.
> Make SenderRatchet parameters configurable

- .github/workflows/checks.yml
- .github/workflows/tests.yml
This PR separates clippy & format checks from the tests workflow. It could be that clippy checks were not producing annotations because of the multiple targets defined for the tests.
> Separate clippy & format checks from tests

- cli/src/user.rs
- delivery-service/ds/src/test.rs
- interop_client/src/main.rs
- openmls/src/extensions/test_extensions.rs
- openmls/src/framing/test_framing.rs
- openmls/src/framing/validation.rs
- openmls/src/group/core_group/apply_proposals.rs
- openmls/src/group/core_group/create_commit.rs
- openmls/src/group/core_group/new_from_external_init.rs
- openmls/src/group/core_group/process.rs
- openmls/src/group/core_group/proposals.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/core_group/test_core_group.rs
- openmls/src/group/core_group/test_duplicate_extension.rs
- openmls/src/group/core_group/test_external_init.rs
- openmls/src/group/core_group/test_proposals.rs
- openmls/src/group/core_group/validation.rs
- openmls/src/group/errors.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/messages/errors.rs
- openmls/src/messages/tests/test_pgs.rs
- openmls/src/prelude.rs
- openmls/tests/test_encoding.rs
- openmls/tests/test_group.rs
- openmls/tests/test_mls_group.rs
- openmls/tests/utils/mls_utils/mod.rs
This PR refactors proposal queues and in the process
- gets rid of the `CreationProposalQueue` and the associated implementations and structs
- gets rid of the `apply_proposal` function (thus fixing #565)
- Removes the `Staged...` prefix whenever it's followed by `Proposal...`, as these structs are now used both for creation and staging
The advantage of the `CreationProposalQueue` was that it relied on references rather than full `Proposal` structs. However, in the course of #617 we started returning a `StagedProposalQueue` at the end of `create_commit`, so the cloning was taking place in any case.
This PR is mostly renaming an code removal with the exception of `filter_proposals`, where I had to clone a proposal where previously a reference was created.
> Refactor proposal queues

- openmls/src/group/core_group/new_from_external_init.rs
- openmls/src/group/core_group/new_from_welcome.rs
- openmls/src/schedule/mod.rs
This fixes some of the clippy warnings that snuck in while the clippy CI was broken. I'm still not sure what to do about the number `decrypt_path` inputs. I'm tempted to put this off until we got rid of the explicit `version` handling.
> Fix most clippy warnings

- interop_client/src/main.rs
- openmls/src/group/core_group/create_commit.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/test_core_group.rs
- openmls/src/group/mls_group/membership.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/mls_group/updates.rs
- openmls/src/treesync/diff.rs
- openmls/src/treesync/treekem.rs
- openmls/tests/test_group.rs
Since we're now relying on the stored `StagedCommit` to remember data from a commit, we don't need to return (and store in case of the `MlsGroup`) a `KeyPackageBundle` whenever we create a commit.
This PR removes the returned `KeyPackageBundle` throughout the `create_commit` chain of calls through the stack and thus fixes #673.
> Remove unnecessary `KeyPackageBundle` return during commit processing

- openmls/src/group/core_group/create_commit_params.rs
- openmls/src/group/core_group/new_from_external_init.rs
- openmls/src/group/core_group/process.rs
- openmls/src/group/core_group/test_external_init.rs
- openmls/src/group/core_group/validation.rs
- openmls/src/group/errors.rs
- openmls/src/group/mls_group/application.rs
- openmls/src/group/mls_group/creation.rs
- openmls/src/group/mls_group/errors.rs
- openmls/src/group/mls_group/exporting.rs
- openmls/src/group/mls_group/membership.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/mls_group/ser.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/group/mls_group/updates.rs
- openmls/src/test_utils/test_framework/client.rs
This PR allows clients that want to join a group via an External Init to process their own staged commit. This was already possible after #659, but this PR introduces proper state transitions in the `MlsGroup`.
This PR is part of the larger effort to enable the external init process, which is tracked in #630.
> Enable processing of own external commits

- openmls/src/framing/test_framing.rs
- openmls/src/group/mls_group/errors.rs
- openmls/src/group/mls_group/membership.rs
- openmls/src/group/mls_group/updates.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/group/tests/test_validation.rs
- openmls/src/test_utils/test_framework/mod.rs
- openmls/src/tree/secret_tree.rs
- openmls/src/tree/sender_ratchet.rs
- openmls/src/tree/tests_and_kats/unit_tests/test_sender_ratchet.rs
- openmls/tests/test_mls_group.rs
This PR enforces immediate forward secrecy when encrypting messages, i.e. the encryption key gets deleted right away.
It introduces automatic storing of standalone proposals in the `MlsGroup`'s proposal store, since we can no longer decrypt our own proposals.
The alternative would be to hand out the proposals in the same way we hand out our own commits and expect the consumer to manually store them in the proposal store once the DS signaled there are no conflicts.
That would be more in line with how we treat other messages. I went for the simpler option for now, because the alternative would lead to quite a few code changes. If we have consensus on the alternative I can change it.
Fixes #243.
> Improve FS when encrypting messages

- openmls/src/group/tests/mod.rs
- openmls/src/group/tests/test_encoding.rs
- openmls/src/group/tests/test_framing.rs
- openmls/src/group/tests/test_group.rs
- openmls/src/group/tests/utils.rs
- openmls/tests/test_decryption_key_index.rs
- openmls/tests/test_interop_scenarios.rs
- openmls/tests/test_key_packages.rs
- openmls/tests/test_managed_api.rs
- openmls/tests/utils/mod.rs
Fixes #644.
This PR moves previous `CoreGroup` integration tests so they become unit tests. The test utils they use are also moved.
Not sure how well GH will detect the move, but the only code changes that were made are to accommodate the new position of the tests.
> Make CoreGroup integration tests unit tests

- openmls/src/framing/codec.rs
- openmls/src/framing/errors.rs
- openmls/src/framing/message.rs
- openmls/src/framing/plaintext.rs
- openmls/src/framing/validation.rs
- openmls/src/group/mls_group/application.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/test_mls_group.rs
Fixes #265.
This PR introduces two opaque type for MLS messages: `MlsMessageIn` and `MlsMessageOut`. The types are identical, the distinction is for the added benefit of type safety.
While this doesn't change the current functionality, it is a step towards making `Mls(Plain|Cipher)text` messages crate-only in order to further restrict the public API.
> Introduce byte buffers for messages

- interop_client/src/main.rs
This PR gets rid of `CoreGroup` in the interop client.
The functionality was not changed, however, I noticed by looking at the old code that the Commit checks (CommitRequest/CommitResponse) were probably not functional. This will have to be fixed when we work on the client again.
The client still uses the `test-utils` feature because it needs access to the KAT vectors. This can probably be changed at some point if we drop that feature and introduce a dedicated feature for the interop client. See  #691.
Fixes  #687.
> Use MlsGroup in interop client

- openmls/src/framing/ciphertext.rs
- openmls/src/framing/test_framing.rs
- openmls/src/framing/validation.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/new_from_external_init.rs
- openmls/src/group/core_group/new_from_welcome.rs
- openmls/src/group/core_group/past_secrets.rs
- openmls/src/group/core_group/process.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/core_group/test_core_group.rs
- openmls/src/group/core_group/test_past_secrets.rs
- openmls/src/group/mls_group/creation.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/mls_group/ser.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/group/tests/utils.rs
- openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
In order to use KeyPackageRefs we need to restructure the way the message
decryption works. This PR is a step in this direction by moving the
message_secrets_store into the CoreGroup and having one way of getting it.
This is not guaranteed to fully make the KeyPackageRef work but is a step in
this direction.
Other changes:
Derypting ciphertext is in two steps now, sender data and actual ciphertext.
This will make it again easier to use KeyPackageRef because the two
decryption steps (header and payload) are separated.
> Move message_secrets_store into CoreGroup

- .github/workflows/fuzz.yml
- openmls/fuzz/Cargo.toml
- openmls/fuzz/fuzz_targets/mls_message_decode.rs
- openmls/fuzz/fuzz_targets/mls_plaintext_decode.rs
- openmls/src/extensions/test_extensions.rs
- openmls/src/framing/ciphertext.rs
- openmls/src/framing/mod.rs
- openmls/src/framing/plaintext.rs
- openmls/src/framing/validation.rs
- openmls/src/group/core_group/apply_proposals.rs
- openmls/src/group/core_group/create_commit.rs
- openmls/src/group/core_group/create_commit_params.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/new_from_external_init.rs
- openmls/src/group/core_group/past_secrets.rs
- openmls/src/group/core_group/process.rs
- openmls/src/group/core_group/proposals.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/core_group/test_duplicate_extension.rs
- openmls/src/group/core_group/validation.rs
- openmls/src/group/mls_group/creation.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mod.rs
- openmls/src/group/tests/mod.rs
- openmls/src/group/tests/test_encoding.rs
- openmls/src/group/tests/test_validation.rs
- openmls/src/messages/proposals.rs
- openmls/src/prelude_test.rs
This PR reduces the visibility of `MlsPlaintext` and `MlsCiphertext` to crate-only. As a consequence, `CoreGroup` could also now become crate-only as intended.
Unused functions are dropped and minor changes are made to accommodate the change.
This will need more work as outlined in #691, but I want to keep it simple for now.
> Reduce visibility

- openmls/src/schedule/message_secrets.rs
- openmls/src/tree/index.rs
- openmls/src/tree/secret_tree.rs
- openmls/src/tree/sender_ratchet.rs
- openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
- openmls/src/tree/treemath.rs
Renaming tree::index::LeafIndex and tree::index::NodeIndex to
SecretTreeLeafIndex and SecretTreeNodeIndex resp.
> rename tree::index types

- .github/workflows/gh-pages.yml
As discussed, it's better to manually publish the mdBook when publishing new releases. This can be invoke from [here](https://github.com/openmls/book/actions/workflows/gh-pages.yml).
> Remove trigger for mdBook

- openmls/src/lib.rs
- openmls/src/treesync/mod.rs
#722 [Bug] treesync::node::Node is private but public API needs it
For now exposing treesync and node so that I can get unblocked.
> [Bug] treesync::node::Node is private but public API needs it

- openmls/src/binary_tree/array_representation/treemath.rs
- openmls/src/binary_tree/test_binary_tree.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/tests/test_external_commit_validation.rs
- openmls/src/tree/treemath.rs
- openmls/src/treesync/tests_and_kats/kats/kat_tree_kem.rs
- openmls/src/treesync/treekem.rs
This PR does the following:
- Fixes clippy errors in the binary tree tests by suppressing it 
- Fixes clippy warnings
- Renames functions that were prefixed with `unsafe_` (but that were actually not unsafe) to avoid any confusion in the future
> Fix clippy errors

- openmls/src/lib.rs
This PR enables clippy linting for missing documentation on public types.
We should have done this a long time ago.
> Introduce missing public docs linting

- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/new_from_welcome.rs
- openmls/src/group/core_group/proposals.rs
- openmls/src/group/mls_group/creation.rs
- openmls/src/group/mls_group/membership.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/mls_group/updates.rs
- openmls/src/prelude.rs
- openmls/src/schedule/kat_key_schedule.rs
I reviewed #141 and #284 and came to the conclusion that we already implemented all the changes. We even implemented some more recent changes regarding the PSK secrets and the key schedule.
The only part that is left is a public API to use PSKs with `MlsGroup`. I have created #751 for that and this is now mentioned in the code.
Fixes #141.
Fixes #284.
> Review older PSK spec changes

- cli/src/identity.rs
- delivery-service/ds/src/test.rs
- memory_keystore/src/lib.rs
- openmls/src/group/core_group/test_core_group.rs
- openmls/src/group/mls_group/application.rs
- openmls/src/group/mls_group/exporting.rs
- openmls/src/group/mls_group/membership.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/group/mls_group/updates.rs
- openmls/src/group/tests/test_external_commit_validation.rs
- openmls/src/group/tests/test_past_secrets.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/group/tests/utils.rs
- openmls/src/schedule/kat_key_schedule.rs
- openmls/src/schedule/psk.rs
- openmls/src/schedule/unit_tests.rs
- openmls/src/test_utils/test_framework/client.rs
- openmls/src/test_utils/test_framework/mod.rs
- openmls/tests/book_code.rs
- openmls/tests/test_mls_group.rs
- traits/src/key_store.rs
Note that the memory key store simply uses the provided bytes as key.
This is not recommended for production systems as this might get
large.
fixes #656
> use byte slice for key store key

- cli/Cargo.toml
- delivery-service/ds-lib/Cargo.toml
- delivery-service/ds/Cargo.toml
- evercrypt_backend/Cargo.toml
- evercrypt_backend/src/lib.rs
- interop_client/Cargo.toml
- memory_keystore/Cargo.toml
- openmls/Cargo.toml
- openmls/benches/benchmark.rs
- openmls/fuzz/Cargo.toml
- openmls/src/test_utils/mod.rs
- openmls_rust_crypto/Cargo.toml
- openmls_rust_crypto/src/lib.rs
- traits/Cargo.toml
This drops the local dependencies in various crates, which should fix a dependency issue when using the crates from crates.io.
> Drop local dependencies in crates

- book/src/user_manual/processing.md
- openmls/src/framing/mod.rs
- openmls/src/framing/sender.rs
- openmls/src/group/core_group/proposals.rs
- openmls/src/group/mls_group/membership.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/tests/mod.rs
- openmls/src/group/tests/test_remove_operation.rs
- openmls/src/prelude.rs
- openmls/tests/book_code.rs
This PR introduces the `RemoveOperation` `enum` that helps interpret the semantic value of a remove proposal when inspecting proposals that are covered by a Commit.
Fixes #623.
> Introduce RemoveOperation

- openmls/src/framing/test_framing.rs
- openmls/src/group/core_group/create_commit.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/new_from_external_init.rs
- openmls/src/group/core_group/new_from_welcome.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/core_group/test_core_group.rs
- openmls/src/group/core_group/test_duplicate_extension.rs
- openmls/src/group/core_group/test_proposals.rs
- openmls/src/group/errors.rs
- openmls/src/group/group_context.rs
- openmls/src/group/mls_group/creation.rs
- openmls/src/group/mod.rs
- openmls/src/group/tests/kat_transcripts.rs
- openmls/src/schedule/errors.rs
- openmls/src/schedule/kat_key_schedule.rs
- openmls/src/schedule/mod.rs
- openmls/src/schedule/psk.rs
- openmls/src/tree/sender_ratchet.rs
- openmls/src/treesync/diff.rs
- openmls/src/treesync/errors.rs
- openmls/src/treesync/mod.rs
- openmls/src/treesync/treesync_node.rs
This PR continues with the error cleanup:
- I wrote a [wiki article](https://github.com/openmls/openmls/wiki/Error-management-in-OpenMLS) explaining the overall error management strategy (will be part of the book later)
- `WelcomeError`/`ExternalCommitError` are public and in near-final state (except for documentation)
- Refactoring in TreeSync/TreeSyncDiff/ABinaryTree API to return LibraryError more often
- more than 50% of the errors now use `thiserror`
Sorry for the large PR again, most of it should be easy to review though.
> Error cleanup 2

- openmls/src/framing/errors.rs
- openmls/src/framing/message.rs
- openmls/src/framing/mod.rs
- openmls/src/framing/sender.rs
- openmls/src/framing/validation.rs
- openmls/src/messages/mod.rs
Fixes #769.
Note that I could turn some types into `pub(crate)` and I'm therefore only touching the public docs.
> Fix framing rustdocs

- LICENSE
- README.md
- cli/Cargo.toml
- delivery-service/ds-lib/Cargo.toml
- delivery-service/ds/Cargo.toml
- interop_client/Cargo.toml
This PR updates the readme, fixes a few links and changes the authors in a few Cargo.toml files to `OpenMLS Authors`.
Fixes #796.
> README update and Cargo.toml updates

- interop_client/src/main.rs
- openmls/Cargo.toml
- openmls/src/ciphersuite/signature.rs
- openmls/src/credentials/mod.rs
- openmls/src/error.rs
- openmls/src/group/mls_group/config.rs
- openmls/src/group/mls_group/errors.rs
- openmls/src/group/tests/test_commit_validation.rs
- openmls/src/group/tests/test_external_commit_validation.rs
- openmls/src/group/tests/test_framing_validation.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/group/tests/test_wire_format_policy.rs
- openmls/src/key_packages/mod.rs
- openmls/src/lib.rs
- openmls/src/prelude.rs
- openmls/tests/test_mls_group.rs
This PR
- makes documentation of public items mandatory
- prohibits using private items in public documentation
- adds documentation for the MlsGroup config
> clean up MlsGroup config and harder rustdoc requirements

- openmls/src/group/mls_group/mod.rs
- openmls/src/lib.rs
- openmls/src/treesync/mod.rs
This PR removes the re-exports from `lib.rs`, as discussed previously. It doesn't address #852 fully yet.
> Remove re-exports from lib.rs

- openmls/src/framing/mod.rs
- openmls/src/framing/validation.rs
- openmls/src/group/errors.rs
- openmls/src/group/group_context.rs
- openmls/src/group/mls_group/errors.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/group/mod.rs
- openmls/src/group/tests/test_commit_validation.rs
- openmls/src/group/tests/test_external_commit_validation.rs
- openmls/src/group/tests/test_framing_validation.rs
- openmls/src/group/tests/test_past_secrets.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/group/tests/test_remove_operation.rs
- openmls/src/group/tests/test_wire_format_policy.rs
- openmls/src/prelude.rs
- openmls/src/prelude_test.rs
- openmls/src/test_utils/test_framework/client.rs
- openmls/src/test_utils/test_framework/errors.rs
- openmls/src/test_utils/test_framework/mod.rs
- openmls/src/treesync/mod.rs
This PR tweaks the group API so that it can be used with just `use openmls::group::{errors::*, *};`.
It also exposes the errors of the `framing` module separately and makes a few other minor tweaks.
> Group API tweaks

- .github/workflows/build.yml
With the new added targets, openmls will always be ready for Android platform.
Source: https://crates.io/crates/cargo-ndk
https://github.com/bbqsrc/cargo-ndk/blob/main/README.md#L15-L19
```
rustup target add \
aarch64-linux-android \
armv7-linux-androideabi \
x86_64-linux-android \
i686-linux-android
```
> Enable android targets

- CHANGELOG.md
- openmls/src/group/mls_group/creation.rs
- openmls/src/group/tests/test_external_commit_validation.rs
ProposalStore::new() method visibility is for crate only, so no one is the application can call this method which is required by join_by_external_commit method.
Also there are no public methods which allow temporary proposal to be stored proposals that are received from the DS in between two commit messages by the application before creating group.
https://github.com/openmls/openmls/blob/main/openmls/src/group/core_group/proposals.rs#L27
> [FixUp] join_by_external_commit does not need to request proposal store

- interop_client/Cargo.toml
- interop_client/src/main.rs
This PR updates the dependencies of the interop client to get ahead of https://github.com/openmls/openmls/security/dependabot/1
It also bumps it to the 2021 edition and fixes on clippy warning.
> Update interop client dependencies

- CHANGELOG.md
- openmls/Cargo.toml
This PR prepares release v0.4.1 which fixes the API as mentioned in the CHANGELOG.
> Prepare v0.4.1 release

- CHANGELOG.md
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/ser.rs
- openmls/src/prelude.rs
Expose SerializedMlsGroup because currently MlsGroup expose [load and save](https://github.com/openmls/openmls/blob/main/openmls/src/group/mls_group/mod.rs#L296-L308) methods but that uses serde_json which is not at all optimized. For 2 people group it spits around 60kb of bytes. 
For time being, until #245 is not done, SerializedMlsGroup can be used with [bincode](https://github.com/bincode-org/bincode) to serialize and it outputs ~4075 bytes for 2 people group.
> [Fixup] Expose SerializedMlsGroup until issue #245 is done

- evercrypt_backend/CHANGELOG.md
- evercrypt_backend/Cargo.toml
- evercrypt_backend/src/provider.rs
- memory_keystore/CHANGELOG.md
- memory_keystore/Cargo.toml
- memory_keystore/src/lib.rs
- openmls/src/key_store.rs
- openmls_rust_crypto/CHANGELOG.md
- openmls_rust_crypto/Cargo.toml
- openmls_rust_crypto/src/provider.rs
- traits/CHANGELOG.md
- traits/src/key_store.rs
- traits/src/random.rs
I've noticed that majority of errors have been migrated to thiserror. This PR transitions public errors from support crates to derive `std::error::Error` as well.
> Use thiserror in support crates

- openmls/Cargo.toml
- openmls_rust_crypto/src/provider.rs
Until #877 is fixed and a new version of the `tls_codec` crate is released OpenMLS should build against `tls_codec` main.
> tls codec main

- openmls/src/framing/validation.rs
I think I noticed a bug in the documentation (`validation.rs`).
* `UnverifiedMemberMessage` -> `UnverifiedGroupMessage`
* `UnverifiedExternalMessage` -> `UnverifiedPreconfiguredMessage`
> fix(docs): Fix description of validation.

- openmls/src/group/core_group/create_commit.rs
- openmls/src/group/core_group/new_from_welcome.rs
- openmls/src/group/core_group/test_core_group.rs
- openmls/src/group/core_group/test_duplicate_extension.rs
- openmls/src/group/group_context.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/messages/codec.rs
- openmls/src/messages/mod.rs
- openmls/src/messages/tests/test_welcome.rs
This PR is work towards #979 and closes #569.
It does the following (from commit messages):
* refactor: Rename `GroupInfoPayload::other_extensions` to `GroupInfoPayload::extensions`.
* refactor: Introduce `GroupInfoPayload::group_context` field.  
* Use `group_context` instead of `GroupInfoPayload::{group_id, epoch, ...}`.
* This fixes #569.
* refactor: Rename `GroupInfoPayload` to `GroupInfoTBS`.
* docs: Add documentation to `GroupInfo{,TBS}`.
The commits are "clean" and can be review one-by-one.
> Sync `GroupInfo{,TBS}` with draft-ietf-mls-protocol-16.

- openmls/src/ciphersuite/aead.rs
- openmls/src/framing/ciphertext.rs
- openmls/src/framing/test_framing.rs
- openmls/src/group/core_group/apply_proposals.rs
- openmls/src/group/core_group/create_commit.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/new_from_welcome.rs
- openmls/src/group/core_group/past_secrets.rs
- openmls/src/group/core_group/process.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/core_group/test_core_group.rs
- openmls/src/group/mls_group/processing.rs
Some mutable borrows were required in some methods, especially `process_unverified_message` whereas it was not required.
Removing them makes the methods intent clearer, helps working with borrow checker rules and could also have runtime advantages.
> Removed unrequired mutable borrows

- openmls/src/treesync/hashes.rs
- openmls/src/treesync/treesync_node.rs
> Rename `ParentNodeTreeHashInput` to `ParentNodeHashInput`.

- .github/workflows/benches.yml
- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/cli.yml
- .github/workflows/clippy.yml
- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/ds.yml
- .github/workflows/fuzz.yml
- .github/workflows/gh-pages.yml
- .github/workflows/interop_client.yml
- .github/workflows/tests.yml
This closes #1062.
Explanation:
GitHub Actions allows to define a concurrency group -- as a string -- for a workflow. Two workflow runs in the same group will be sequenced by default. By using `cancel-in-progress: true` we cancel the superseded ones instead. This is useful because, often, we commit small changes such as reviewer suggesstions in the review process. These additional commits spawn new workflow runs that run *in addition* to the (now superseded) pending workflow runs.
I propose to cancel these as fast as possible to make the CI more responsive and to not waste computing power.
By putting the workflow into the concurrency group name ...
```yaml
group: ${{ github.workflow }}-${{ github.ref }}
```
... we make sure that a workflow A does not cancel a workflow B. Thus, …
> ci: Eagerly cancel superseded workflows.

- openmls/src/messages/mod.rs
> docs: Use C-style comments in TLS presentation syntax.

- openmls/src/group/tests/kat_transcripts.rs
- openmls/src/schedule/kat_key_schedule.rs
This is a followup to #1077. I propose to aim for zero warnings. Otherwise they tend to accumulate :-)
> chore: Silence temporary warnings.

- .github/workflows/fuzz.yml
- openmls/Cargo.toml
- openmls/fuzz/Cargo.toml
- openmls/src/ciphersuite/codec.rs
- openmls/src/ciphersuite/kdf_label.rs
- openmls/src/ciphersuite/mac.rs
- openmls/src/ciphersuite/mod.rs
- openmls/src/ciphersuite/signature.rs
- openmls/src/extensions/capabilities_extension.rs
- openmls/src/extensions/ratchet_tree_extension.rs
- openmls/src/extensions/required_capabilities.rs
- openmls/src/group/core_group/create_commit.rs
- openmls/src/group/group_context.rs
- openmls/src/group/mod.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/group/tests/kat_transcripts.rs
- openmls/src/group/tests/test_commit_validation.rs
- openmls/src/messages/mod.rs
- openmls/src/messages/proposals.rs
- openmls/src/messages/tests/test_codec.rs
- openmls/src/treesync/hashes.rs
- openmls/src/treesync/node/codec.rs
- openmls/src/treesync/node/parent_node.rs
- openmls/src/treesync/treekem.rs
- openmls/src/treesync/treesync_node.rs
- traits/Cargo.toml
- traits/src/types.rs
Progress towards #877.
It updates all TLS syntax to use variable length encoding except for some places where code will change as part of larger spec changes. Hence this is not closing #877 yet but the remaining work will most likely happen in other issues. I'll keep #877 upon until that's happened.
> Update most TLS syntax to variable length

- openmls/src/ciphersuite/hash_ref.rs
Fixes https://github.com/openmls/openmls/issues/735.  I added domain separation in https://github.com/openmls/openmls/pull/1054, but with incorrect strings.
> Update hash reference labels

- openmls/src/binary_tree/array_representation/diff.rs
- openmls/src/treesync/diff.rs
- openmls/src/treesync/hashes.rs
- openmls/src/treesync/treesync_node.rs
Fixes #927.
Note that there are no tests because this PR only changes the input to a hash, this will be tested during interop.
> Add a marker byte to tree hash input structs

- openmls/src/extensions/mod.rs
This closes #955.
#955 is an editorial change as it only adds "external_senders" to the extension list.
However, given that we might want to update/improve the presentation language due to an editorial change, I think that we can use this issue as a reason to introduce the presentation language. But we can also just close #955 without linking it to this PR.
> docs: Add presentation language to `Extension{,Type}`.

- openmls/src/framing/sender.rs
- openmls/src/framing/validation.rs
- openmls/src/group/core_group/process.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/errors.rs
- openmls/src/group/mls_group/errors.rs
- openmls/src/group/tests/test_proposal_validation.rs
This closes #1087. The `ExternalSender` extension will be introduced in #1085.
> Rename "Preconfigured" to "External".

- openmls/src/framing/ciphertext.rs
- openmls/src/framing/codec.rs
- openmls/src/framing/message.rs
- openmls/src/framing/plaintext.rs
- openmls/src/framing/test_framing.rs
- openmls/src/framing/validation.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/validation.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/group/tests/kat_transcripts.rs
- openmls/src/group/tests/test_commit_validation.rs
- openmls/src/group/tests/test_encoding.rs
- openmls/src/group/tests/test_external_commit_validation.rs
- openmls/src/group/tests/test_framing.rs
- openmls/src/group/tests/test_framing_validation.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
This PR contains a few changes towards the updated wire format and framing structure in draft 16. It is meant as an intermediate PR towards #979.
* Rename `MlsPlaintextTbs` to `MlsContentTbs`
* Rename `VerifiableMlsPlaintext` to `VerifiableMlsAuthContent`
* Restructure `MlsContentTbs` s.t. it contains `MlsContent` rather than its individual parts
> Changes towards draft-16 wire format

- openmls/src/framing/ciphertext.rs
- openmls/src/framing/codec.rs
- openmls/src/framing/plaintext.rs
- openmls/src/group/tests/test_framing_validation.rs
Another PR towards fixing #979. This one introduces the `MlsContentAuthData` struct and integrates it into other structs like `MlsCiphertextContent` and `MlsPlaintext`.
> Introduce MlsContentAuthData

- .github/workflows/clippy.yml
- .github/workflows/coverage.yml
I suspect that github.ref is from main for pull_request_target jobs such that these jobs get cancelled all the time.
> Disable concurrency groups for clippy/coverage

- book/src/message_validation.md
- openmls/src/framing/validation.rs
- openmls/src/group/core_group/process.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/core_group/validation.rs
- openmls/src/group/tests/test_external_commit_validation.rs
This PR validates proposals included in an external commit by using an allowlist rather than a denylist as before. Proposals allowed in an external commit are : `ExternalInit`, `Remove` & `PreSharedKey`.
Note that I merged (and rephrased) ValSem242 & ValSem243 and also shifted the others ValSem[244..247]
Note: **There are no tests to verify PSK proposals are supported (and their cardinality) since it is not supported by external commits.** And I couldn't find any issue tracking this. Is this in draft-16 scope ? If not we should probably create an issue to track that down.
Fixes #878
> feat: use an allowlist for validating external commit proposals

- CHANGELOG.md
- book/src/user_manual/processing.md
- cli/src/user.rs
- delivery-service/ds/src/test.rs
- interop_client/src/main.rs
- openmls/src/framing/mod.rs
- openmls/src/framing/validation.rs
- openmls/src/group/core_group/process.rs
- openmls/src/group/mls_group/errors.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/group/mod.rs
- openmls/src/group/tests/external_proposal.rs
- openmls/src/group/tests/test_commit_validation.rs
- openmls/src/group/tests/test_external_commit_validation.rs
- openmls/src/group/tests/test_framing_validation.rs
- openmls/src/group/tests/test_past_secrets.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/group/tests/test_remove_operation.rs
- openmls/src/group/tests/test_wire_format_policy.rs
- openmls/src/test_utils/test_framework/client.rs
- openmls/src/test_utils/test_framework/errors.rs
- openmls/tests/book_code.rs
- openmls/tests/test_mls_group.rs
This PR fixes #1088.
It introduces the following changes:
- Message processing becomes easier because we can now drop the parsing step. `MlsMessageIn` can now be processed directly.
- `ProcessedMessage` now also consistently exposes header values (epoch, sender, aad, etc.). The content is exposed through `.content()` or `.into_content()` and is equivalent to the old enum that has now been renamed to `ProcessedMessageContent`.
- The API change revealed that most ValSem positive tests were not entirely correct (as well as a few other tests), this has now been fixed.
The first commit contains the relevant code changes, the other commits only contain the adjustments to the new API and the test fixes.
> Remove signature key indirection

- .github/workflows/docs.yml
This PR enables the building of rust docs by the CI on PRs in addition to pushes to main.
> enable docs-building by CI on PRs

- book/src/forward_secrecy.md
- book/src/user_manual/join_from_welcome.md
- openmls/src/group/tests/test_framing_validation.rs
No sources modification have been required for this one as 2 commits with the same epoch were already failing when the message was parsed. Anyway, added a test to make sure it happened.  
Then, documented in the book that both commits and welcome messages should be dealt with caution and nothing should be merged locally before the Delivery Service approves the message.
Fixes #939
> handle conflicting commits

- openmls/Cargo.toml
- openmls/src/group/core_group/mod.rs
The lifetimes can be infered by now and the typetag crate isn't used anymore.
> remove unnecessary lifetimes

- book/src/SUMMARY.md
- book/src/introduction.md
- book/src/message_validation.md
- book/src/performance.md
- book/src/traits/traits.md
- book/src/traits/types.md
- book/src/user_manual/README.md
- book/src/user_manual/add_members.md
- book/src/user_manual/create_group.md
- book/src/user_manual/create_key_package.md
- book/src/user_manual/crypto-subtle.md
- book/src/user_manual/join_from_welcome.md
- book/src/user_manual/leaving.md
- book/src/user_manual/remove_members.md
The book markdown hasn't been formatted in a while.
To avoid churn while working on it I did a pass. There should only be whitespace changes and things like `*` -> `-` here.
Review without whitespace changes.
> auto format book markdown

- openmls/src/binary_tree/array_representation/diff.rs
- openmls/src/binary_tree/array_representation/mod.rs
- openmls/src/binary_tree/array_representation/sorted_iter.rs
- openmls/src/binary_tree/array_representation/tree.rs
- openmls/src/binary_tree/test_binary_tree.rs
- openmls/src/treesync/diff.rs
- openmls/src/treesync/mod.rs
This is a follow-up PR to #1155.
It removes `NodeId` in the binary tree & introduces a new iterator for more efficient node/leaf inspection.
> More tree cleanup

- openmls/src/extensions/codec.rs
- openmls/src/extensions/mod.rs
- openmls/src/extensions/test_extensions.rs
- openmls/src/framing/plaintext.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/mls_group/config.rs
- openmls/src/group/mls_group/creation.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/group/tests/test_encoding.rs
- openmls/src/group/tests/test_group.rs
- openmls/src/group/tests/utils.rs
- openmls/src/key_packages/mod.rs
- openmls/src/key_packages/test_key_packages.rs
- openmls/src/test_utils/test_framework/client.rs
- openmls/src/treesync/mod.rs
- openmls/src/treesync/node/leaf_node.rs
- openmls/src/treesync/node/leaf_node/lifetime.rs
- openmls/tests/book_code.rs
This PR replaces #1154 to only remove the lifetime extension.
The lifetime is part of the leaf node now instead.
Note that there are different mechanisms to set the lifetime that are not aligned well. This will be cleaned up in follow ups.
> Remove LifetimeExtension

- openmls/src/extensions/codec.rs
- openmls/src/extensions/errors.rs
- openmls/src/extensions/mod.rs
This PR introduces an `Extensions` type that should eventually replace all instances of `Vec<Extension>` and generally unify extension handling. Specifically, `Extensions` ensures that there are no duplicate extensions. Thus, this PR is a step towards closing #720.
Some preliminary notes:
This PR only introduces the `Extensions` struct for now. The replacement of `Vec<Extension>` everywhere requires quite some mechanical changes. The last time I worked on this, I proposed to introduce a `KeyPackageBundleBuilder` first to get rid of many `Extensions::empty/default()` calls. This is why we decided to close the last PR.
The functions are a bit repetitive but I think this is worth it given that they are easy to maintain and will eventually simplify some more complex code.
As discussed …
> feat: Introduce `Extensions` type.

- cli/src/identity.rs
- delivery-service/ds-lib/tests/test_codec.rs
- delivery-service/ds/src/test.rs
- interop_client/src/main.rs
- openmls/benches/benchmark.rs
- openmls/src/group/core_group/create_commit.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/group/tests/test_past_secrets.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/group/tests/utils.rs
- openmls/src/key_packages/mod.rs
- openmls/src/key_packages/test_key_packages.rs
- openmls/src/lib.rs
- openmls/src/messages/tests/test_welcome.rs
- openmls/src/test_utils/test_framework/client.rs
- openmls/tests/book_code.rs
- openmls/tests/key_store.rs
- openmls/tests/test_external_commit.rs
- openmls/tests/test_mls_group.rs
This PR introduces a `KeyPackageBuilder`. This simplifies `KeyPackage` creation and reduces the times when we have to touch the tests. Specifically, changing all instances of `Vec<Extension>` to `Extensions` would require to touch all `KeyPackage::create` instances. After this PR is merged, this is not needed anymore. Thus, in a way, I see this as preliminary work towards closing #720.
> feat: Introduce `KeyPackageBuilder`.

- openmls/src/group/core_group/new_from_welcome.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/messages/codec.rs
- openmls/src/messages/mod.rs
- openmls/src/messages/tests/test_welcome.rs
This implementation should not exist because it can be used to bypass signature verification.
This closes #1181.
> fix: Remove `GroupInfo`s `tls_codec::Deserialize` implementation. 

- openmls/src/ciphersuite/signable.rs
- openmls/src/ciphersuite/signature.rs
- openmls/src/credentials/mod.rs
- openmls/src/framing/mls_auth_content.rs
- openmls/src/framing/test_framing.rs
- openmls/src/framing/validation.rs
- openmls/src/group/core_group/create_commit.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/new_from_external_init.rs
- openmls/src/group/core_group/new_from_welcome.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/core_group/test_core_group.rs
- openmls/src/group/errors.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/group/tests/kat_transcripts.rs
- openmls/src/group/tests/test_commit_validation.rs
- openmls/src/group/tests/test_external_commit_validation.rs
- openmls/src/group/tests/test_framing.rs
- openmls/src/group/tests/test_group.rs
- openmls/src/group/tests/utils.rs
- openmls/src/key_packages/errors.rs
- openmls/src/key_packages/mod.rs
- openmls/src/key_packages/test_key_packages.rs
- openmls/src/messages/tests/test_export_group_info.rs
- openmls/src/messages/tests/test_welcome.rs
- openmls/src/treesync/node/leaf_node.rs
This PR makes `sign` and `verify` operations in the `signable` module use only the keys rather than the credential. This is a step towards removing the keys from the credential structs.
Invocations still get the keys from the credential sometimes. This is in order not to have to do everything in one go and allow for other work like #1185 to proceed.
> signable with keys

- CHANGELOG.md
- interop_client/src/main.rs
- openmls/src/group/mls_group/updates.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/test_utils/test_framework/client.rs
- openmls/src/test_utils/test_framework/mod.rs
- openmls/src/treesync/node/leaf_node.rs
Another followup to #819.
Update proposals operate on leaf nodes now, not key packages. This PR changes the API that this is reflect this. For this to work I also introduce a public `generate` function on the `LeafNode` to generate leaf nodes without key packages.
> update with leaf node

- openmls/src/group/tests/kat_messages.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/key_packages/mod.rs
- openmls/src/treesync/mod.rs
- openmls/src/treesync/node/leaf_node.rs
This (rather) resolves openmls/annotations#33 and resolves an `xxx:`s on the way.
> Allow to pass `Capabilities` and `Extensions` when creating an `OpenMlsLeafNode`.

- openmls/src/extensions/required_capabilities.rs
- openmls/src/extensions/test_extensions.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/test_proposals.rs
- openmls/src/treesync/node/leaf_node.rs
This closes #1200.
Note: I used `CredentialType::Basic` to fixup the tests. However, this is not checked for now. I recommend to review commit-by-commit. The first commit just aligns the field names and renames the corresponding methods.
> spec: Add `RequiredCapabilitiesExtension.credential_types` field.

- book/src/user_manual/join_from_external_commit.md
- cli/src/networking.rs
- cli/src/user.rs
- delivery-service/ds/src/test.rs
- interop_client/src/main.rs
- openmls/src/group/core_group/create_commit.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/errors.rs
- openmls/src/group/group_context.rs
- openmls/src/group/mls_group/membership.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/group/mls_group/updates.rs
- openmls/src/group/tests/external_proposal.rs
- openmls/src/group/tests/test_commit_validation.rs
- openmls/src/group/tests/test_external_commit_validation.rs
- openmls/src/group/tests/test_framing_validation.rs
- openmls/src/group/tests/test_past_secrets.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/group/tests/test_remove_operation.rs
- openmls/src/group/tests/test_wire_format_policy.rs
- openmls/src/lib.rs
- openmls/src/messages/mod.rs
- openmls/src/messages/tests/test_welcome.rs
- openmls/src/schedule/mod.rs
- openmls/src/test_utils/test_framework/client.rs
- openmls/src/test_utils/test_framework/mod.rs
- openmls/tests/book_code.rs
- openmls/tests/test_external_commit.rs
- openmls/tests/test_mls_group.rs
Closes #1150 
First I'm sorry for the big PR. The reason is that because of the signature change, a lot of tests were affected. 
The biggest use case for this feature is to return the `GroupInfo` in order to make a join with external commit. Docs were added to the book with an example explaining how to do it.
We have opted for returning an optional since this only makes sense if the the ratchet tree is required. OpenMls doesn't support specifying required capabilities as of now (should we open a new issue for that?) and the default behavior in the `RequiredCapabilitiesExtension` is to support everything as can be seen [here](https://github.com/openmls/openmls/blob/main/openmls/src/extensions/required_capabilities.rs#L79-L91). For that reason we opted for checking the …
> feat: Return group info on stage commit

- .github/workflows/coverage.yml
~I couldn't find a "timeout" in GitHub actions but assumed it should mean "seconds". Minutes would exceed the default `timeout-minutes: 360`, which is likely not what we want. Given that 500 seconds are roughly 10 minutes and the job is taking longer, I removed the timeout altogether. The added `version` should fix the rest. Not sure why there was a `cargo clean` but it doesn't seem necessary.~
This PR switches the coverage measurement from tarpaulin to grcov.
> ci: Fix coverage job.

- openmls/src/group/core_group/proposals.rs
- openmls/src/messages/codec.rs
- openmls/src/messages/proposals.rs
As a reminder: Everything that *has* a `draft-ietf-mls-protocol-XX` is guaranteed to be from `XX`. If `XX` is lower than we want or there is no mention we should check and update.
Edit: I also updated `Proposal`. The functional change is that `group_context_extensions` is now `0x0007` and `app_ack` is now `0x0008`. I saw this and wanted to already fix it in light of upcoming interop testing.
> docs/spec: Update `Proposal`s to draft-ietf-mls-protocol-17.

- openmls/src/group/core_group/staged_commit.rs
- openmls/src/treesync/node/leaf_node.rs
- openmls/src/treesync/node/leaf_node/capabilities.rs
- openmls/src/treesync/node/leaf_node/codec.rs
This is a pure refactoring. Thus, I used `pub use capabilities::*` to re-export and `pub(crate)` for access control. Edit: Also added two `TODO`s. Edit: While at it, I also improved the readability of the `leaf_node.rs` file. I'll split the file into distinct typestate modules in a follow-up. (This PR is best reviewed commit-by-commit.)
> refactor/chore: Move `Capabilities` into own module + Improve readability of `leaf_node.rs`.

- openmls/src/ciphersuite/secret.rs
- openmls/src/messages/mod.rs
- openmls/src/schedule/mod.rs
- openmls/src/tree/secret_tree.rs
It is useful for debugging to `Debug`-print `GroupSecrets`. Thus, I implemented it quickly.
> chore/docs: Improve `Debug`ing (+ chore)

- openmls/src/framing/test_framing.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/new_from_welcome.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/errors.rs
- openmls/src/group/public_group/diff.rs
- openmls/src/messages/tests/test_welcome.rs
- openmls/src/schedule/kat_key_schedule.rs
- openmls/src/schedule/mod.rs
- openmls/src/treesync/treekem.rs
This PR makes it so that the decryption of the encrypted group secrets takes the encrypted group info as context. Notably, it was required to adapt a test because it can now not happen that the ciphersuite mismatches.
> spec: Use `encrypted_group_info` as context in decryption of welcome secrets.

- openmls/src/framing/test_framing.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/new_from_external_init.rs
- openmls/src/group/core_group/new_from_welcome.rs
- openmls/src/group/core_group/process.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/core_group/test_core_group.rs
- openmls/src/group/core_group/test_external_init.rs
- openmls/src/group/core_group/test_proposals.rs
- openmls/src/group/mls_group/membership.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/updates.rs
- openmls/src/group/public_group/mod.rs
- openmls/src/group/public_group/validation.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/group/tests/test_commit_validation.rs
- openmls/src/group/tests/test_encoding.rs
- openmls/src/group/tests/test_group.rs
- openmls/src/group/tests/tree_printing.rs
- openmls/src/group/tests/utils.rs
- openmls/src/treesync/mod.rs
This PR removes the `TreeSync` getter in `PublicGroup`, thus better enforcing the `PublicGroup` abstraction.
This PR also fixes what I believe is a small bug in `check_extension_support`, although the function is currently only used in tests.
There might be other, smaller things to clean up, but I think we should leave that for the public API grooming before the next release. I would thus say, this fixes #1255.
> Improve `PublicGroup` abstraction

- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/process.rs
- openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
This PR factors out the decryption process in `CoreGroup` message processing and adds two getters for test purposes.
> Small refactor of CoreGroup message processing

- openmls/src/messages/proposals.rs
This was a pending draft change that didn't make it.
> Require path for GroupContextExtensions

- Cargo.toml
- basic_credential/Cargo.toml
- cli/Cargo.toml
- delivery-service/ds-lib/Cargo.toml
- delivery-service/ds/Cargo.toml
- interop_client/Cargo.toml
- openmls/Cargo.toml
- openmls_rust_crypto/Cargo.toml
- traits/Cargo.toml
This moves the tls_codec to the workspace to avoid specifying the version everywhere.
> move tls_codec dependency to workspace

- openmls/src/group/core_group/kat_passive_client.rs
- openmls/src/group/core_group/new_from_welcome.rs
- openmls/src/group/core_group/test_core_group.rs
- openmls/src/group/errors.rs
- openmls/src/group/tests/test_commit_validation.rs
- openmls/src/schedule/errors.rs
- openmls/src/schedule/kat_psk_secret.rs
- openmls/src/schedule/psk.rs
- openmls/src/schedule/unit_tests.rs
While it is certainly not the last PR that reworks PSK handling, it should unblock interoperability work. I made it a draft because there are a few `TODO`s left.
> refactor: Store PSKs independently from nonce.

- openmls/src/credentials/mod.rs
- openmls/src/credentials/tests.rs
- openmls/src/messages/proposals.rs
This PR adds the `{Credential,Proposal}Type::Unknown` variants. I think this is all that is needed here. It must not happen that we receive an actual proposal that we don't understand. If it would, there would be no way to parse it. This is different for extensions as they are designed to have an easily "skippable" payload.
> interop: Implement support for unknown `{Credential,Proposal}Type`s.

- interop_client/src/main.rs
The MlsClient proto added a free method, add it to the implementation so all tests can compile and run.
> Add free method to MlsClient to match proto

- interop_client/Cargo.toml
- interop_client/README.md
- interop_client/src/main.rs
This PR improves the readability of the interop runner, improves the logging, adjusts AD, and adjusts the config so that the interop scenarios can pass. It is unfortunately a bit difficult to review due to some renamings. I think these are an improvement but could understand if we want to revert. The motivation behind the changes is that we can now see very well where a specifc log item is coming from. This proved to be very helpful in tracing down the cause of various mismatches.
This PR is a basis for the next ones that implement support for PSK, external join, and fix a transcript hash error. So, I hope it is one of the last PRs in this series.
> interop: Add some fixes to interop runner + chore.

- interop_client/src/main.rs
Fix build break in how log is being used (introduced by merge conflict). 
Fix warning about unused variable by logging it like other methods do.
> Fix build break and warnings in interop_client

- .github/workflows/interop.yml
I do expect the new "interop" job to fail because we don't have support for group context extensions proposals for now. Also, the job will take quite long the first time it is run (~35 minutes). Afterwards, all VCPKG's should be cached and it will take roughly a few minutes.
Edit: I should add another commit that explicitly filters the errors due to group context extensions with a `TODO`. This way, CI will be green and @augustocdias could rebase #1361 and remove the `TODO` from this job.
> interop/ci: Test interop between OpenMLS and MLS++.

- openmls/Cargo.toml
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/ser.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/tests/book_code.rs
- openmls/tests/test_mls_group.rs
- traits/src/key_store.rs
Hi everyone,
In order to fix #245 once and for all, we could opt to store `MlsGroup`s within the backing Keystore.
This allows three things: 
* To solve the serialization format issues as it is deferred to the Keystore's `store|read` implementations - Becomes a non-concern openmls-wise
* To remove the runtime dependency on `serde_json` (goes to dev-dependencies)
* Remove the only possible surface-level API that returns a system-dependent IO error
What do you think?
> fix: Store MlsGroup state in keystore

- Cargo.toml
This pre-release of `tls_codec` allows the use of `SecretVLBytes`, which implements `ZeroizeOnDrop`. This will be useful in the context of #1369.
> Bump tls codec version to 0.3.0-pre.3

- book/src/message_validation.md
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/new_from_welcome.rs
- openmls/src/group/errors.rs
- openmls/src/group/public_group/staged_commit.rs
- openmls/src/group/public_group/validation.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/treesync/node/encryption_keys.rs
- openmls/src/treesync/node/leaf_node.rs
- openmls/src/treesync/node/leaf_node/capabilities.rs
- openmls/src/treesync/treekem.rs
Fixes #1186.
Fixes #412.
This PR adds more leaf node validation. In particular, it unifies how duplicate keys are detected in one test. It also introduces capabilities checks and unifies overlapping validation code.
This PR however does not introduce comprehensive testing and instead defers to #1378, #1379, #580 and #581.
> More LeafNode validation

- book/src/SUMMARY.md
- book/src/user_manual/credential_validation.md
Fixes #938.
Since OpenMLS doesn't handle credentials, this is not applicable directly. However, I added a section to the book.
> Add credential validation section to book

- openmls/src/treesync/node/encryption_keys.rs
This fixes a small bug that is unlikely to cause any real-world issues.
The EncryptionKeyPair struct has the wrong `MlsEntityId`. There's a small possibility (probably well under 0.1%) that a HPKE keypair generates the same public key as one of the signature public keys and ends up erasing it, breaking everything.
> fix: EncryptionKeyPair has the wrong MlsEntityId

- openmls/src/tree/sender_ratchet.rs
Currently the documented value for `out_of_order_tolerance` in `SenderRatchetConfiguration` is different from the actually used value:
https://github.com/comawill/openmls/blob/246c96b827099701cf4a2fef022e93c6f1c0afd2/openmls/src/tree/sender_ratchet.rs#L58
This PR updates the documented value to `5` to align with the used value.
Setting the value in the code to a value below 5 leads to CI tests failing.
With default setting `out_of_order_tolerance < 5` the following tests fail:
* tree::tests_and_kats::unit_tests::test_secret_tree::test_boundaries::case_1_rust_crypto_MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
* tree::tests_and_kats::unit_tests::test_secret_tree::test_boundaries::case_2_rust_crypto_MLS_128_DHKEMP256_AES128GCM_SHA256_P256
* …
> Set documented default value of `out_of_order_tolerance` to value used in code

- evercrypt_backend/Cargo.toml
- evercrypt_backend/src/provider.rs
- openmls/Cargo.toml
- openmls/src/ciphersuite/aead.rs
- openmls/src/ciphersuite/codec.rs
- openmls/src/ciphersuite/mac.rs
- openmls/src/ciphersuite/mod.rs
- openmls/src/ciphersuite/secret.rs
- openmls/src/group/core_group/kat_passive_client.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/key_packages/mod.rs
- openmls/src/messages/mod.rs
- openmls/src/messages/tests/test_welcome.rs
- openmls/src/schedule/mod.rs
- openmls/src/test_utils/mod.rs
- openmls/src/treesync/node/encryption_keys.rs
- openmls_rust_crypto/src/provider.rs
- traits/Cargo.toml
- traits/src/crypto.rs
- traits/src/types.rs
Closes #1240 
This wraps sensitve variables into new types that will implement `Zeroize` and will zero the memory on drop. Unfortunately we can't use the `VLBytes` in that case and I had to switch to the regular `Vec<u8>`.
I've moved the `HpkePrivateKey` struct to the `traits` crate and since for testing `PartialEq` and `Eq` are required I had to introduce the `test-utils` feature in it.
> feat: wrap sensitive types in order to zero the memory on drop (#1240)

- openmls/src/group/core_group/mod.rs
- openmls/src/group/mls_group/config.rs
- openmls/src/group/public_group/builder.rs
- openmls/src/key_packages/lifetime.rs
- openmls/src/key_packages/mod.rs
- openmls/src/treesync/mod.rs
- openmls/src/treesync/node/leaf_node.rs
Hi!
While testing we found an API regression: It is no longer possible to set a lifetime/expiration for a KeyPackage while it was possible in 0.4.x.
This PR moves the `lifetime.rs` file within the `key_package` module, exposing it publicly, and adds the proper methods on the builder to use it.
> fix: Regression on setting KeyPackage lifetimes

- openmls/src/group/core_group/staged_commit.rs
- openmls/tests/book_code.rs
A simple PR that introduces a getter for the `EpochAuthenticator` of the group state that is represented by a staged commit.
> Allow access to authenticator from staged commit

- openmls/src/group/core_group/proposals.rs
- openmls/tests/test_mls_group.rs
When adding group members via the MlsGroup API, the new members do not necessarily end up in the tree in the same order as they are in the slice of KeyPackages that is the input of the API call. This PR fixes that and adds a test.
> Ensure Add proposal order is maintained; add test

- openmls/Cargo.toml
As per [documentation](https://doc.rust-lang.org/cargo/reference/manifest.html#the-keywords-field):
> [crates.io](https://crates.io/) has a maximum of 5 keywords. Each keyword must be ASCII text, start with a letter, and only contain letters, numbers, _ or -, and have at most 20 characters.
> fix keywords for crate.io

- basic_credential/Cargo.toml
- basic_credential/src/lib.rs
- openmls/src/ciphersuite/tests/kat_crypto_basics.rs
- openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
- openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
- openmls_rust_crypto/Cargo.toml
- openmls_rust_crypto/src/provider.rs
This PR updates the ed25519-dalek crate to version 2.0 in the rust crypto provider and basic credential crates. Due to the updated API of ed25519-dalek, we no longer need to encode the private key as a concatenation of public and private key.
This PR also updates the aes-gcm and the chacha20poly1305 crates to their newest versions.
> upgrade rust crypto libraries

- openmls/src/tree/secret_tree.rs
Removes potentially panicking indexing from the secret tree. Fixes #1253, since the other points mentioned there have been previously fixed (#1252).
> Make the secret tree panic free

- traits/src/key_store.rs
The requirement might have made sense at some point, but is an unnecessary restriction now.
> Remove Send + Sync requirement for key store

- openmls/Cargo.toml
- openmls/src/error.rs
backtrace has > 10 dependencies (transitively) which might make it difficult for applications to import it, and consequently using openmls.
> Make backtrace crate an optional dependency.

- traits/src/traits.rs
Send + Sync was removed from `OpenMlsKeyStore` but not `OpenMlsProvider` in #1440. This PR brings the change over to OpenMlsProvider.
`OpenMlsCrypto` is still Send + Sync. Can change that in this PR too if that's desired
> Relax Send + Sync from OpenMlsProvider

- openmls_rust_crypto/README.md
Fixes the link to the openmls_traits crate's README.
> Fix link to traits in openmls_rust_crypto README

- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/mls_group/test_mls_group.rs
In order to validate the credentials of the leaf node in the optional update path of a staged commit, the caller needs to be able to access it. They can now do so using the new method `update_path_leaf_node`.
Unfortunately the change on line 156 made the line so wide that the entire `if let`-block afterwards shifted indentation.
I have not yet written any tests because I am unfamiliar with the testing infrastructure. Any help with that is appreciated.
Fixes #1460
> Add `update_path_leaf_node` method to `StagedCommit`.

- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/messages/proposals.rs
- openmls/src/test_utils/test_framework/client.rs
- openmls/src/test_utils/test_framework/mod.rs
- openmls/tests/test_decryption_key_index.rs
- openmls/tests/test_interop_scenarios.rs
- openmls/tests/test_managed_api.rs
A StagedCommit can carry credentials in several different places,
all of which have to be verified. To make this easier on the caller,
we add the `credentials_to_verify` method on StagedCommit, which returns
an iterator over all the credentials in a StagedCommit that need to
be verified.
Also we add infrastructure in test_framework for letting the test code
decide which credentials would pass validation, by passing in a closure
that takes a &Credential and returns a bool, as well as a simple test
that serves as an example for how to use the function.
Fixes #1469
> Add credentials_to_verify method to StagedCommit

- book/src/user_manual/create_group.md
- openmls/src/extensions/errors.rs
- openmls/src/extensions/test_extensions.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/mls_group/builder.rs
- openmls/src/group/mls_group/config.rs
- openmls/src/group/mls_group/errors.rs
- openmls/src/group/public_group/builder.rs
- openmls/tests/book_code.rs
Currently, only two kinds of extensions can be set for the initial group context, and they both have their own method on the builder to set them. In order to be able to add arbitrary extensions, this PR adds a method `with_group_context_extensions` to the group builders, that sets an arbitrary set of extensions. The set is of type `Extensions`, so we know that each extension is only set once.
Any RequiredCapability extension mentioned in that set will be overwritten, and if ExternalSenders is specified using the dedicated method, that one is preferred and the one provided using `with_group_context_extensions` is dropped.
> Add `with_group_context_extensions` method to group builders

- book/src/user_manual/group_config.md
- openmls/src/extensions/errors.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/mls_group/builder.rs
- openmls/src/group/mls_group/config.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/group/public_group/builder.rs
- openmls/tests/book_code.rs
This PR adds (and tests) a way to add leaf node extensions and capabilities when creating a new group using the MlsGroup builder pattern.
> Add leaf node configuration options to MlsGroup builder

- CHANGELOG.md
- book/src/user_manual/group_config.md
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/test_proposals.rs
- openmls/src/group/mls_group/builder.rs
- openmls/src/group/mls_group/config.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/group/public_group/builder.rs
- openmls/src/group/tests/external_remove_proposal.rs
- openmls/tests/book_code.rs
This PR removes the dedicated `required_capabilities` and `external_senders` fields (along with their getters and setters) in favor of the `group_context_extension` field. This makes processing during group creation easier.
> Clean up `MlsGroup*` builders

- .github/workflows/build.yml
- .github/workflows/tests.yml
- book/src/SUMMARY.md
- book/src/user_manual/wasm.md
- openmls/Cargo.toml
- openmls/src/binary_tree/array_representation/kat_treemath.rs
- openmls/src/ciphersuite/tests/kat_crypto_basics.rs
- openmls/src/group/core_group/test_core_group.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/kat_vl.rs
- openmls/src/key_packages/lifetime.rs
- openmls/src/lib.rs
- openmls/src/schedule/kat_key_schedule.rs
- openmls/src/schedule/kat_psk_secret.rs
- openmls/src/test_utils/mod.rs
- openmls/src/test_utils/test_framework/mod.rs
- openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
- openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
- openmls/src/tree/tests_and_kats/kats/secret_tree.rs
- openmls/src/treesync/node/parent_node.rs
- openmls/src/treesync/tests_and_kats/kats/kat_tree_operations.rs
- openmls/src/treesync/tests_and_kats/kats/kat_tree_validation.rs
- openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
- openmls/src/treesync/treekem.rs
This PR enables most (but not all!) tests for Wasm. We don't run the tests using wasm-pack, instead we use [this approach](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/usage.html#appendix-using-wasm-bindgen-test-without-wasm-pack). The reason is that using wasm_pack would require the tests to be public, including the entire module path leading to it. That did not seem feasible.
It also makes some changes so that this actually works:
- disable parallelism for wasm
- rayon: inline conditional compilation chooses whether to use `(into_)iter` or `(into_)par_iter` based on `target_arch`
- disable default features for criterion
- don't use the file system at runtime in tests
- added the `read_json` macro that reads the test vectors at compile time
- somehow it thinks the macro is …
> Enable Wasm Tests

- openmls/src/group/mls_group/config.rs
This PR addresses a single word typo in the rustdoc for the `number_of_resumption_psks` field in the `MlsGroupJoinConfig` struct.
Feel free to dismiss this PR if it is useless.
> docs(openmls): typo in rustdoc for MlsGroupJoinConfig

- openmls/src/group/mls_group/mod.rs
Fix typo in documentation: Member -> External
> Fix typo in documentation

- openmls/src/extensions/required_capabilities.rs
- openmls/src/group/errors.rs
- openmls/src/group/public_group/validation.rs
- openmls/src/treesync/node/leaf_node/capabilities.rs
This PR addresses issue #1487. The problem is that currently the list of extensions in a `GroupContextExtensions` proposal is compared against the capabilities of the current members. Instead, it needs to
1. check that the `RequiredCapabilities` of the group are satisfied by all members of the group
2. check that the types of all extensions in the proposal are in the `RequiredCapabilities`.
This PR also adds a method on the `RequiredCapabilitiesExtension` for checking whether an extension type is supported. This is needed because the extension types defined in the RFC are supported implicitly, so we also have to compare against the defaults. The defaults are defined close to the `Capabilities` struct and used to be private to these modules. I made the one for extension types `pub(crate)` …
> Fix validation bug

- book/src/user_manual/processing.md
- cli/src/user.rs
- delivery-service/ds/src/main.rs
- delivery-service/ds/src/test.rs
- interop_client/src/main.rs
- openmls/src/framing/codec.rs
- openmls/src/framing/errors.rs
- openmls/src/framing/message_in.rs
- openmls/src/framing/message_out.rs
- openmls/src/framing/test_framing.rs
- openmls/src/group/core_group/kat_passive_client.rs
- openmls/src/group/core_group/kat_welcome.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/group/tests/external_add_proposal.rs
- openmls/src/group/tests/external_remove_proposal.rs
- openmls/src/group/tests/test_commit_validation.rs
- openmls/src/group/tests/test_external_commit_validation.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/group/tests/test_wire_format_policy.rs
- openmls/src/lib.rs
- openmls/src/prelude.rs
- openmls/tests/book_code.rs
- openmls/tests/test_external_commit.rs
Fixes #1494.
This PR does the following:
- Fixes and expands the section about message processing in the book
- Introduces a `TryFrom` conversion from `MlsMessageIn` into `ProtocolMessage`
- Renames `MlsMessage[In/Out]Body` to `MlsMessageBody[In/Out]` to harmonize it with the naming scheme used by other structs
- Refactors the tests because the old way to convert `MlsMessageIn` into `ProtocolMessage` is no longer possible
> Improve processing

- .github/workflows/coverage.yml
- openmls/src/framing/mls_auth_content.rs
- openmls/src/group/core_group/proposals.rs
Fixes #347.
The context is explained [here](https://github.com/openmls/openmls/issues/347#issuecomment-1937815975), this PR just gets rid of an unnecessary `.clone()`.
> Remove unnecessary cloning of proposals

- .github/workflows/coverage.yml
- openmls/src/framing/errors.rs
- openmls/src/framing/private_message.rs
- openmls/src/framing/private_message_in.rs
- openmls/src/framing/test_framing.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/proposals.rs
- openmls/src/group/core_group/test_core_group.rs
- openmls/src/group/errors.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/group/tests/external_remove_proposal.rs
- openmls/src/group/tests/kat_messages.rs
- openmls/src/group/tests/test_commit_validation.rs
- openmls/src/group/tests/test_external_commit_validation.rs
- openmls/src/group/tests/test_group.rs
- openmls/src/treesync/errors.rs
- openmls/src/treesync/mod.rs
Fixes #645.
This PR does the following:
- Remove test functions from the CoreGroup that are not useful along with the corresponding tests.
- Moves code in `core_group/mod.rs`
- Refactor unnecessary errors
- Minor renaming
> Cleanup unused CoreGroup methods

- basic_credential/src/lib.rs
- cli/Cargo.toml
- cli/src/networking.rs
- cli/src/user.rs
- delivery-service/ds-lib/Cargo.toml
- delivery-service/ds-lib/src/lib.rs
- delivery-service/ds/Cargo.toml
- fuzz/fuzz_targets/key_package_decode.rs
- fuzz/fuzz_targets/mls_message_decode.rs
- fuzz/fuzz_targets/proposal_decode.rs
- fuzz/fuzz_targets/welcome_decode.rs
- openmls/src/key_packages/mod.rs
- openmls/src/lib.rs
- openmls/src/prelude.rs
- openmls/src/treesync/tests_and_kats/tests.rs
- openmls/tests/book_code.rs
- openmls/tests/test_external_commit.rs
- openmls/tests/test_mls_group.rs
- traits/src/signatures.rs
- traits/src/types.rs
This PR exposes the whole `tls_crate` in the prelude (and cleans up the fallout).
Applications using OpenMLS no longer have to import `tls_codec` separately this way. For various projects depending on OpenMLS this has been painful because of the frequent version changes.
> Expose the whole tls_codec crate in prelude

- CHANGELOG.md
- cli/src/identity.rs
- cli/src/user.rs
- delivery-service/ds-lib/tests/test_codec.rs
- delivery-service/ds/src/test.rs
- interop_client/src/main.rs
- openmls-wasm/src/lib.rs
- openmls/benches/benchmark.rs
- openmls/src/credentials/errors.rs
- openmls/src/credentials/mod.rs
- openmls/src/credentials/tests.rs
- openmls/src/extensions/external_sender_extension.rs
- openmls/src/extensions/test_extensions.rs
- openmls/src/group/tests/external_remove_proposal.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/group/tests/utils.rs
- openmls/src/key_packages/mod.rs
- openmls/src/key_packages/test_key_packages.rs
- openmls/src/lib.rs
- openmls/src/test_utils/mod.rs
- openmls/src/test_utils/test_framework/client.rs
- openmls/src/test_utils/test_framework/mod.rs
- openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
- openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
- openmls/src/treesync/node/leaf_node/capabilities.rs
- openmls/tests/book_code.rs
- openmls/tests/key_store.rs
Fixes #1526 
This PR makes `BasicCredential` more ergonomic, because it can now be converted from a `Credential` without having to serialize and deserialize the content of the credential. It also checks the input size of the indentity.
> Improve BasicCredential

- CHANGELOG.md
- cli/src/user.rs
- delivery-service/ds/src/test.rs
- interop_client/src/main.rs
- openmls-wasm/src/lib.rs
- openmls/src/extensions/test_extensions.rs
- openmls/src/group/core_group/kat_passive_client.rs
- openmls/src/group/mls_group/creation.rs
- openmls/src/group/mls_group/test_mls_group.rs
- openmls/src/group/public_group/tests.rs
- openmls/src/group/tests/external_add_proposal.rs
- openmls/src/group/tests/test_commit_validation.rs
- openmls/src/group/tests/test_framing_validation.rs
- openmls/src/group/tests/test_past_secrets.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/group/tests/test_remove_operation.rs
- openmls/src/group/tests/test_wire_format_policy.rs
- openmls/src/lib.rs
- openmls/src/messages/tests/test_welcome.rs
- openmls/src/test_utils/test_framework/client.rs
- openmls/src/treesync/tests_and_kats/tests.rs
- openmls/tests/book_code.rs
- openmls/tests/test_mls_group.rs
In #1506 we not only added the StagedWelcome types, but also made the methods to create them consume an MlsMessageIn instead of a Welcome. This was done at the time because there was the open issue #1326 that asked to do this, and we didn't check whether that really was a good idea.
It wasn't.
This PR keeps StagedWelcome, but makes the method that create these structs a Welcome instead of a MlsMessageIn.
Fixes #1519.
> Make StagedWelcome consume Welcome instead of MlsMessageIn

- cli/src/identity.rs
- cli/src/user.rs
- delivery-service/ds-lib/src/lib.rs
- delivery-service/ds-lib/tests/test_codec.rs
- delivery-service/ds/src/test.rs
- interop_client/src/main.rs
- openmls-wasm/src/lib.rs
- openmls/benches/benchmark.rs
- openmls/src/credentials/mod.rs
- openmls/src/extensions/external_sender_extension.rs
- openmls/src/extensions/test_extensions.rs
- openmls/src/framing/mls_content.rs
- openmls/src/group/core_group/kat_passive_client.rs
- openmls/src/group/core_group/test_core_group.rs
- openmls/src/group/tests/external_remove_proposal.rs
- openmls/src/group/tests/test_commit_validation.rs
- openmls/src/group/tests/test_proposal_validation.rs
- openmls/src/group/tests/utils.rs
- openmls/src/key_packages/mod.rs
- openmls/src/key_packages/test_key_packages.rs
- openmls/src/lib.rs
- openmls/src/test_utils/mod.rs
- openmls/src/test_utils/test_framework/client.rs
- openmls/src/test_utils/test_framework/mod.rs
- openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
- openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
- openmls/src/treesync/tests_and_kats/tests.rs
- openmls/tests/book_code.rs
- openmls/tests/key_store.rs
- openmls/tests/test_mls_group.rs
This PR further improves credential handling. Since [we assume](https://github.com/openmls/openmls/blob/main/openmls/src/credentials/mod.rs#L219) that all credentials are variable-size vectors we might as well simplify things.
This way handling basic credentials and custom credentials alike becomes easier.
> Further improve credentials

- .github/workflows/interop.yml
Due to a recent [`vcpkg`](https://github.com/microsoft/vcpkg/pull/38017) failure (in turn due to a bug in [CMake](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9390)), this PR disables interop testing with MLS++ on CI.
> Disable MLS++ interop on CI

- .github/workflows/build.yml
- openmls/Cargo.toml
- openmls/src/binary_tree/array_representation/treemath.rs
- openmls/src/ciphersuite/secret.rs
- openmls/src/schedule/mod.rs
- openmls/src/schedule/psk.rs
This fixes the build issues introduced in #1548.
It also adds a `cargo hack check` command to ensure all features are built on ci.
> fixup build after #1548

- openmls/src/group/mls_group/mod.rs
`PublicGroup` already has a function that allows the caller to get the (future) index of an external sender. This PR makes that function accessible via the `MlsGroup` API.
> Expose getter for ext_sender_index function

- openmls/src/group/mls_group/test_mls_group.rs
Related to https://github.com/openmls/openmls/issues/1549
The idea of the test is basically to show that we can  save and update data to Group Context Extensions that all group members can read via Unknown Group Context Extension and Group Context Extension proposals.
> Adds test for updating Unknown Group Context Extension

- basic_credential/src/lib.rs
In order to call `StorageProvider` functions that require a `SignaturePublicKey` we need the `StorageId` to be accessible.
Also adds a from function so you can get a storage id from a public key vec
For example
```rust
let signature_keys = SignatureKeyPair::new(CIPHERSUITE.signature_algorithm());
let public_key = StorageId::from(signature_keys.to_public_vec());
storage_provider.write_signature_key_pair::<StorageId, SignatureKeyPair>(&public_key, &signature_keys);
```
> Make StorageId Public

- memory_storage/src/lib.rs
- traits/src/storage.rs
Using `read_list` has the same effect here, but it's the wrong function really.
> Return an empty vector in storage.aad when it's not found

- memory_storage/src/lib.rs
- memory_storage/src/test_store.rs
- memory_storage/tests/proposals.rs
- openmls/src/group/mls_group/mod.rs
- traits/src/storage.rs
The memory storage clear proposal function is working now. This required a small change to the storage API such that we know the ProposalRef type.
There's also a test for the proposals in the storage crate now.
> Proposal storage update

- openmls/Cargo.toml
This PR makes backtrace an optional feature in order to make the library faster in non-debug builds.
fixes #1598
> Make backtrace an optional feature

- .github/workflows/benches.yml
- memory_storage/src/lib.rs
- memory_storage/src/persistence.rs
- openmls/Cargo.toml
- openmls/benches/large-balanced-group.rs
- openmls/examples/large-groups.rs
- openmls/src/binary_tree/array_representation/diff.rs
- openmls/src/binary_tree/array_representation/tree.rs
- openmls/src/group/core_group/mod.rs
- openmls/src/group/core_group/past_secrets.rs
- openmls/src/group/core_group/proposals.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/public_group/diff.rs
- openmls/src/group/public_group/mod.rs
- openmls/src/group/public_group/staged_commit.rs
- openmls/src/schedule/message_secrets.rs
- openmls/src/schedule/mod.rs
- openmls/src/schedule/psk.rs
- openmls/src/treesync/diff.rs
- openmls/src/treesync/mod.rs
- openmls/src/treesync/treesync_node.rs
- openmls_rust_crypto/Cargo.toml
- openmls_rust_crypto/src/lib.rs
- openmls_rust_crypto/src/provider.rs
This PR adds facilities to run benchmarks on larger groups.
Design
- not criterion based
- ability read/write group state into files for testing larger groups
- different group setups
- cli interface to quickly test different scenarios
This required a few small changes to OpenMLS library code to derive some more `Clone`s for testing (benchmarking). Also, the memory key store can be written to files now.
Closes #1596
> Some more benchmarks

- openmls/Cargo.toml
This version drops the test_vectors folders and reduces the compressed package to 373KiB
> openmls v0.6.0-pre.2

- openmls/src/group/mls_group/mod.rs
- openmls/src/group/tests_and_kats/tests/encoding.rs
- openmls/src/group/tests_and_kats/tests/framing.rs
- openmls/src/group/tests_and_kats/utils.rs
- openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
- openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
Migrates all remining tests to use `MlsGroup` rather than `CoreGroup`, except for one test which is already migrated as part of #1629.
> Migrate remaining `CoreGroup` tests to `MlsGroup`

- CHANGELOG.md
- openmls/src/group/core_group/mod.rs
- openmls/src/group/public_group/mod.rs
This is a follow-up to #1637: We also remove `serde` from the `PublicGroup` to make things consistent.
> Remove serde for PublicGroup and CoreGroup

- memory_storage/src/lib.rs
- memory_storage/src/test_store.rs
- traits/src/public_storage.rs
- traits/src/storage.rs
Some of the naming in the storage provider was not consistent, this PR corrects that.
> Align storage provider naming

- CHANGELOG.md
- openmls/src/framing/validation.rs
- openmls/src/group/core_group/new_from_external_init.rs
- openmls/src/group/core_group/new_from_welcome.rs
- openmls/src/group/core_group/process.rs
- openmls/src/group/errors.rs
- openmls/src/group/mls_group/application.rs
- openmls/src/group/mls_group/errors.rs
- openmls/src/group/mls_group/exporting.rs
- openmls/src/group/mls_group/membership.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/mls_group/proposal.rs
- openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
- openmls/src/group/public_group/mod.rs
- openmls/src/group/public_group/process.rs
- openmls/src/group/public_group/tests.rs
- openmls/src/group/tests_and_kats/tests/external_add_proposal.rs
- openmls/src/group/tests_and_kats/tests/external_commit_validation.rs
- openmls/src/group/tests_and_kats/tests/external_remove_proposal.rs
- openmls/src/group/tests_and_kats/tests/framing_validation.rs
- openmls/src/group/tests_and_kats/tests/group_context_extensions.rs
- openmls/src/group/tests_and_kats/tests/proposal_validation.rs
- openmls/src/test_utils/test_framework/client.rs
- openmls/src/test_utils/test_framework/errors.rs
- openmls/src/test_utils/test_framework/mod.rs
- openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
- openmls/tests/book_code.rs
- openmls/tests/mls_group.rs
It was impossible to instantiate a `PublicGroup` without implementing a full `StorageProvider` (via `OpenMlsProvider`), this PR removes that requirement.
> Remove OpenMlsProvider dependency of PublicGroup.

- openmls/src/group/core_group/process.rs
- openmls/src/group/core_group/staged_commit.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/tests_and_kats/tests/past_secrets.rs
In `CoreGroup::merge_staged_commit` we forgot persisting the new message secrets. This PR addresses this. As part of testing this, I also updated the test to use separate providers for different group members.
> Fix Missing Persisting of Message Secrets

- basic_credential/Cargo.toml
- delivery-service/ds/Cargo.toml
- libcrux_crypto/Cargo.toml
- memory_storage/Cargo.toml
- openmls/Cargo.toml
- openmls_rust_crypto/Cargo.toml
- openmls_test/Cargo.toml
- traits/Cargo.toml
Bump versions for the next round of prereleases, and bump `time` (a transitive dependency) in the DS to fix [this problem](https://github.com/time-rs/time/issues/681).
> Bump versions and fix build error

- openmls/src/group/public_group/validation.rs
- openmls/src/group/tests_and_kats/tests/remove_operation.rs
This PR adds check 701 from [the dashboard](https://validation.openmls.tech/) and a basic test. It doesn't properly test validation for incoming messages, because I wanted more checks done instead of futzing with Frankenstein messages for now.
> Add check and (basic) test for check 701: remove can't contain inde to blank leaf

- CONTRIBUTING.md
The link to the code of conduct was broken, this PR just fixes that.
> Fix a broken link in `CONTRIBUTING.md`

- openmls/src/ciphersuite/hpke.rs
- openmls/src/extensions/mod.rs
- openmls/src/group/mls_group/builder.rs
- openmls/src/group/mls_group/membership.rs
- openmls/src/key_packages/lifetime.rs
- openmls/src/key_packages/mod.rs
- openmls/src/messages/proposals.rs
XMTP has been maintaining their own fork of OpenMLS. Here we take some of their changes and bring them back into this tree. We are also looking at making it easier to build commits with multiple kinds of proposals, but would prefer a different API.
This PR also incorporates XMTP's fix for the test submitted in #1660.
> Upstream some changes from XMTP

- openmls/Cargo.toml
The docs link of the openmls pointed at github. That's broken now. But it should really link to docs.rs.
> Fix docs link

- CHANGELOG.md
- openmls/src/extensions/mod.rs
- openmls/src/group/mls_group/commit_builder.rs
- openmls/src/group/mls_group/proposal.rs
- openmls/tests/opaque_extension.rs
This PR fixes typos in the name of a commit builder function, adds an getter for unknown extensions in `Extensions` and adds a test case that serves as an example for how to access custom group context extensions, both when joining from a welcome or when processing a commit.
Fixes #1686
> Fix Typo and add GroupContextExtension example for Unknown Extensions

- openmls/src/credentials/mod.rs
- openmls/src/framing/validation.rs
- openmls/src/group/public_group/process.rs
- openmls/src/group/tests_and_kats/tests/group.rs
When reading through the code I found a sketchy looking bit (the removed block in framing/validation.rs). The code looks like it tries to fetch the keys and credentials for messages from old epochs, but a closer read suggest it just tries the same thing again in a convoluted way. Also, it doesn't check for the epoch, it just retries if the lookup failed. This means that it is happy with finding any leaf node, regardless of whether the message epoch matches the group epoch.
So I added a test that provokes a problem: When removing a member and adding a new member, the key material in the leaf node is replaced. If we then receive a message from the old epoch, it should load the wrong key material from the current tree, and signature verification should fail. And that's exactly what's …
> Correctly Look Up Credentials and Public Keys for Members for Previous Epochs

- openmls_rust_crypto/Cargo.toml
Previously, `cargo check --features "test-utils"` in `open_rust_crypto` would produce
```text
Checking openmls_rust_crypto v0.3.0 (/private/tmp/openmls/openmls_rust_crypto)
error[E0277]: the trait bound `MemoryStorage: Clone` is not satisfied
--> openmls_rust_crypto/src/lib.rs:16:5
|
13 | #[cfg_attr(feature = "test-utils", derive(Clone))]
|                                           ----- in this derive macro expansion
...
16 |     key_store: MemoryStorage,
|     ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Clone` is not implemented for `MemoryStorage`
|
= note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)
```
This is because `MemoryStorage` only impls `Clone` when `openmls_memory_storage` crate is built with `test-utils`.
This PR …
> Fixed `openmls_rust_crypto` build with `test-utils` feature

- openmls/src/group/public_group/validation.rs
Add some annotations I had forgotten to do during a previous round. This is the one about allowing to add a member, but only if that member is also being removed in the same commit.
> Add annotations for valn0306

- CHANGELOG.md
- memory_storage/CHANGELOG.md
- memory_storage/src/lib.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/mls_group/staged_commit.rs
- openmls/src/group/tests_and_kats/tests/proposal_validation.rs
This PR fixes two related problems:
- MemoryStorage returned an error if no epoch key pairs could be found. This is a little inconsistent with the other implementations of reader-type functions. Other storage provider implementations are not likely to implement the same semantics, which means it's probably better placed within OpenMLS. This PR thus changes MemoryStorage's return to be an `Ok(vec![])` if no values can be found.
- OpenMLS didn't actually care about any error returned by the storage provider when looking up epoch key pairs, using `unwrap_or_default` instead, which means fix 1 doesn't really have any impact. That's not great, though, so this PR also adds some error handling behaviour s.t. OpenMLS actually detects if something went wrong at the provider.
> Change error in MemoryStorage and result handling in OpenMLS

- openmls/src/ciphersuite/signature.rs
The removed code is never used and never tested.
> Drop dead code in signature.rs

- openmls_rust_crypto/README.md
It's not `-ng` anymore. Also mention hpke-rs.
> Fix x25519-dalek crate link in README

- openmls/tests/mls_group.rs
This PR addresses issue #1243 by adding tests for scenarios in which we create a commit with the proposals [Remove(a), Add(a), Add(a)].
* The test `mls_duplicate_signature_key_detection_different_key_package`: Ensure that duplicate signature key detection is not bypassed when a different key package is used for each Add proposal. This test ensures that the correct error is returned by `MlsGroup::commit_to_pending_proposals()`.
* The test `mls_duplicate_signature_key_detection_same_key_package`: Ensure that duplicate signature key detection is not bypassed when the same key package is used for each Add proposal. This test currently ensures that only one of the Add proposals is kept when creating the commit, and the other one is filtered out.
Fixes #1243
> Test duplicate signature key detection is not bypassed

- openmls/src/binary_tree/tests.rs
This PR disables the test `test_new_tree_error()` due to a segfault on 32-bit platforms (see #1727)
> Disable `test_new_tree_error()` due to segfault

- openmls/src/test_utils/mod.rs
- openmls/src/test_utils/single_group_test_framework/assertions.rs
- openmls/src/test_utils/single_group_test_framework/errors.rs
- openmls/src/test_utils/single_group_test_framework/mod.rs
This pull request adds a lightweight test suite that aims to avoid boilerplate in many of the tests that involve a single group with multiple members. 
It provides functionality for:
- Setting up testing scenarios (creating groups with multiple, arbitrary members)
- Delivering and applying a message for all members of a group where a provided condition is met
- Individually accessing the underlying `MlsGroup`s and performing operations on them in a more granular way
- Asserting correctness of group membership
> Single group test framework

- CHANGELOG.md
- openmls/src/group/mls_group/commit_builder.rs
- openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
- openmls/src/group/mls_group/updates.rs
This PR introduces a new `self_update_with_new_signer` function to `MlsGroup`, as well as a `build_with_new_signer` build option for the `CommitBuilder`. Both can be used to create commits that rotate the creator's signature key.
> add ability to rotate signature keys

- .github/workflows/tests.yml
- CHANGELOG.md
- book/src/SUMMARY.md
- book/src/user_manual/fork-resolution.md
- openmls/Cargo.toml
- openmls/src/ciphersuite/kdf_label.rs
- openmls/src/framing/tests.rs
- openmls/src/group/fork_resolution/mod.rs
- openmls/src/group/fork_resolution/readd.rs
- openmls/src/group/fork_resolution/reboot.rs
- openmls/src/group/mls_group/commit_builder.rs
- openmls/src/group/mls_group/exporting.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/mls_group/tests_and_kats/tests/external_init.rs
- openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
- openmls/src/group/mls_group/tests_and_kats/tests/proposals.rs
- openmls/src/group/mls_group/tests_and_kats/utils.rs
- openmls/src/group/mod.rs
- openmls/src/group/tests_and_kats/tests/group.rs
- openmls/src/tree/sender_ratchet.rs
- openmls/tests/book_code_fork_resolution.rs
This PR adds helpers for resolving forks in MLS groups. A state is forked if the group does not agree on the sequence of commits that were merged. This can happen due to state handling bugs in clients or a buggy DS.
The helpers are implemented on top of MlsGroup. Existing clients can already do this themselves, but the helpers take some of the burden of implementing this manually. They also are behind the `fork-resolution-helpers` feature flag, in order to make it opt-in.
This PR adds helpers based on two different strategies:
1. Remove and Re-Add. This requires the client initiating the resolution to know which members are in a different state. Given that information a commit that first removes all these clients and re-adds them.
2. Reboot the Group. Creates a new group and adds the same …
> Add Helpers for resolving forks

- openmls/src/group/tests_and_kats/tests/key_package_in.rs
- openmls/src/group/tests_and_kats/tests/mod.rs
Add validation test for https://validation.openmls.tech/#valn0108
- `KeyPackageIn::validate()` should return the error `KeyPackageVerifyError::InvalidLeafNodeSourceType` if  `leaf_node_source` is not of the correct enum variant `LeafNodeSource::KeyPackage(_)`
> Add validation test for valn0108

- openmls/src/group/tests_and_kats/tests/capabilities_check.rs
- openmls/src/group/tests_and_kats/tests/mod.rs
- openmls/src/test_utils/single_group_test_framework/errors.rs
- openmls/src/test_utils/single_group_test_framework/mod.rs
This PR adds several validation tests corresponding to https://validation.openmls.tech/#valn0104:
- `test_valn_0104_new_member_unsupported_credential_type()`: Verify that the credential type is supported by all members of the group, as specified by the capabilities field of each member's LeafNode
- `fn test_valn_0104_new_member_capabilities_not_support_all_credential_types()`: Verify that the capabilities field of the [added] LeafNode indicates support for all the credential types currently in use by other members
In addition to these tests, this PR also contains a small update to the `single_group_test_framework` :
- `pub use` the `GroupError` error type (in order to be able to also the error types it wraps) 
-  add error handling for the call to `MlsGroup::add_members()` in …
> Add validation tests for valn0104

- openmls/src/group/public_group/diff/apply_proposals.rs
The RFC says
> The path field MAY be omitted if (a) it covers at least one proposal and (b) none of the proposals covered by the Commit are of "path required" types.
https://www.rfc-editor.org/rfc/rfc9420.html#section-12.4-9
With a negation, this means that a path is required if there is no proposal or at least one proposal requires a path.
---
I also saw these lines were written, probably because of "External Commits MUST contain a path field" https://www.rfc-editor.org/rfc/rfc9420.html#section-12.4.3.2-11.1
// * (or) it is an external commit
|| external_init_proposal_option.is_some()
But this is implied by `proposals_require_path` as far as I can tell:
External commits require "exactly one ExternalInit" proposal (https://www.rfc-editor.org/rfc/rfc9420.html#section-12.2-5), which is a …
> Path Required: Fix wrong negation in code comment

- openmls/src/binary_tree/tests.rs
This PR removes the test `binary_tree::test_new_tree_error()`, which segfaults on 32-bit platforms. 
This test is removed here because it is not guaranteed to work as expected, because the test constructs a vector with a large number of elements, but without initializing the underlying memory.
Fixes #1727
> Remove `binary_tree::test_new_tree_error()` (segfault on 32-bit platforms)

- openmls/src/group/mls_group/errors.rs
- openmls/src/group/mls_group/processing.rs
- openmls/src/group/public_group/process.rs
While the `unimplemented` can't be reached at the moment because it would fail earlier, it's safer to just return errors.
> return error when external sender sends commit

- openmls/src/group/public_group/validation.rs
- openmls/src/treesync/node/leaf_node.rs
This PR adds references to [valn0113](https://validation.openmls.tech/#valn0113)  to the comments in the codebase, to document where this `LeafNode` validation check takes place. This check was recently added to the dashboard, but is already implemented in the proposal validation by the `CommitBuilder`.
These annotations will also allow these locations to be searchable from the `search code` link that is provided in the validation dashboard.
> Add references to validation check valn0113

- openmls/src/framing/message_out.rs
- openmls/src/framing/public_message.rs
- openmls/src/framing/validation.rs
- openmls/src/group/errors.rs
- openmls/src/group/group_context.rs
- openmls/src/group/mls_group/create_commit.rs
- openmls/src/group/mls_group/staged_commit.rs
- openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
- openmls/src/group/public_group/diff/apply_proposals.rs
- openmls/src/group/tests_and_kats/kats/messages.rs
- openmls/src/messages/proposals.rs
- openmls/src/schedule/mod.rs
- openmls/src/treesync/diff.rs
- openmls/src/treesync/errors.rs
- openmls/src/treesync/node/leaf_node.rs
- openmls/tests/interop_scenarios.rs
This PR conservatively drops stale TODOs. The criteria were:
- The issue has been addressed and closed
- The TODOs no longer made sense
> chore: Drop stale TODOs

- CHANGELOG.md
- openmls/src/treesync/mod.rs
- openmls/src/treesync/node/leaf_node.rs
There's a public `leaf_node_source` function that allows getting the `LeafNodeSource` of a leaf. However, the `LeafNodeSource` type is not actually public. This PR fixes that.
> chore: expose LeafNodeSource

- openmls/src/extensions/mod.rs
- openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
This PR upstreams a fix by @neekolas. In the validation function that checks which extension types are valid in leaf nodes, we use the wrong set of extensions. This PR addresses this.
> Fix list of extensions valid in a leaf node

- .github/workflows/tests.yml
- basic_credential/Cargo.toml
- libcrux_crypto/Cargo.toml
- libcrux_crypto/src/crypto.rs
- libcrux_crypto/src/lib.rs
- libcrux_crypto/src/rand.rs
- memory_storage/Cargo.toml
- openmls/Cargo.toml
- openmls_rust_crypto/Cargo.toml
- openmls_rust_crypto/src/provider.rs
- openmls_test/Cargo.toml
- openmls_test/src/lib.rs
- sqlite_storage/Cargo.toml
- traits/CHANGELOG.md
- traits/Cargo.toml
- traits/src/types.rs
This PR updates the libcrux provider to use pure Rust crates where possible (see #1751):
- `libcrux-chacha20poly1305`
- `libcrux-ed25519`
- `libcrux-hkdf`
- `libcrux-sha2`
- `hpke-rs`
For now, in the crypto and rand providers, the `libcrux::drbg::Drbg` is also replaced with a `rand::rngs::ReseedingRng<rand_chacha::ChaCha20Core,rand::rngs::OsRng>`.
This PR also drops AES support from the libcrux provider.
> Update libcrux provider to use pure Rust crates

- book/src/SUMMARY.md
- book/src/user_manual/discarding_commits.md
- openmls/src/test_utils/mod.rs
- openmls/src/test_utils/single_group_test_framework/assertions.rs
- openmls/src/test_utils/single_group_test_framework/mod.rs
- openmls/src/test_utils/storage_state.rs
- openmls/tests/book_code_discard_commit.rs
This PR adds tests and examples (see issue #1723) for cleaning up local state when a Commit needs to be discarded. 
It adds test and examples for Commits containing these types of Proposals:
- Add
- Update (`MlsGroup::self_update_with_new_signer()`)
- Remove
- PreSharedKey
- ExternalInit
- GroupContextExtensions
- SelfRemove
- Custom
It also adds several smaller features to `test_utils::single_group_test_framework`, to further reduce boilerplate in the tests, including:
- Methods to access parts of the relevant state in the storage provider for a `MemberState`
- Assertions that ensure the group-related state in the `StorageProvider` is consistent with a provided state
- A methid to access the `GroupId` from the `GroupState`, and fix a bug where the `GroupId` was not passed in to the …
> Add book examples and tests for discarded Commits

- CHANGELOG.md
- book/src/user_manual/updates.md
- openmls/src/credentials/mod.rs
- openmls/src/group/errors.rs
- openmls/src/group/mls_group/commit_builder.rs
- openmls/src/group/mls_group/mod.rs
- openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
- openmls/src/group/mls_group/updates.rs
- openmls/src/treesync/node/leaf_node.rs
- openmls/tests/book_code.rs
- openmls/tests/book_code_discard_commit.rs
This PR introduces a `NewSignerBundle` struct that allows passing a signer together with a CredentialWithKey when using `self_update_with_new_signer`. `self_update_with_new_signer` now also throws an error if a (non-matching) `CredentialWithKey` is passed in via `LeafNodeParameters`. All this is to avoid passing in mismatching signer and credentials/keys.
> Use SignerBundle instead of Signer for update

- CHANGELOG.md
- openmls/src/group/mls_group/commit_builder.rs
- openmls/src/group/tests_and_kats/tests/group.rs
This PR adds a way to control whether the `CommitBuilder` outputs a GroupInfo. It's backwards-compatible in that the newly added `create_group_info` flag defaults to the `use_ratchet_tree_extension` in the `MlsGroup`s `MlsGroupJoinConfig`.
> feat: group info creation flag in commit builder

- openmls/src/credentials/mod.rs
- openmls/src/group/mls_group/commit_builder.rs
- openmls/src/group/mod.rs
This pull request adds a \`pub use\` declaration for `commit_builder::*` to `openmls/src/group/mod.rs`, alongside the other public exports in this module. In the Rust documentation generated from this crate, the `CommitBuilder` and its documentation will now be included.
This PR also includes missing doc comments for two public methods on `CommitBuilder`, as well as a minor fix to a module-level comment in `openmls/src/credentials/mod.rs`, which previously led to a warning when generating the docs.
> Documentation fixes and pub use `commit_builder::*` 

- openmls/src/group/mls_group/builder.rs
- openmls/src/group/mod.rs
This PR exports `mls_group::builder::*` alongside the other public exports for the `openmls` crate, so that the documentation for the `MlsGroupBuilder` struct will appear in the rustdocs for this crate. 
It also adds a doc comment to `MlsGroupBuilder`.
> export `mls_group::builder::*`

- openmls_test/src/lib.rs
- sqlite_storage/CHANGELOG.md
- sqlite_storage/src/storage_provider.rs
- sqlite_storage/tests/proposals.rs
The sqlite storage provider uses refinery to manage migrations, i.e. creation of tables for storage provider data. So far, the migrations in the provider use the general migrations table used by refinery, which means that it doesn't compose well with external apps that want to use the same DB for other data (and have their own migrations). This PR mitigates that by storing OpenMLS-specific migrations in a separate, named table.
> feat: set migration table name for refinery migrations

- sqlite_storage/src/lib.rs
- sqlite_storage/src/storage_provider.rs
Replace non-existing reference to `SqliteStorageProvider::create_tables` with `SqliteStorageProvider::run_migrations()` in module introduction.
Enhance depreciation warning for `SqliteStorageProvider::initialize()`.
Tested with `cargo doc` to confirm everything renders as expected.
> fix(doc): `SqliteStorageProvider` database initialization

- CHANGELOG.md
- libcrux_crypto/Cargo.toml
- libcrux_crypto/src/crypto.rs
- openmls/src/ciphersuite/mac.rs
- openmls/src/ciphersuite/secret.rs
- openmls/src/test_utils/frankenstein/crypto.rs
- openmls_rust_crypto/src/hmac.rs
- openmls_rust_crypto/src/lib.rs
- openmls_rust_crypto/src/provider.rs
- traits/CHANGELOG.md
- traits/src/crypto.rs
Coses #1375.
Since `OpenMlsCrypto` is also used by `Mac` and `Secret` we also need to add the respective methods here.
Both the rust_crypto and libcrux crypto providers have been updated to implement the new trait. Although `hkdf_expand` could have been used, we opted for the explicit `hmac` implementations provided by both crates for clarity and consistency.
A separate module was created for the HMAC implementation in rust_crypto to resolve import conflicts (multiple applicable methods in the same scope).
The test_utils have also been updated to use the new hmac function.
> adding the hmac function to OpenMlsCrypto

- openmls/src/binary_tree/tests.rs
This fixes the coverage runs (#1819). No idea why this didn't show up earlier.
We still need to properly address #1819. But this fixes the run at least.
Note that https://github.com/openmls/openmls/commit/f24eb69e7b0ad116e3d37129c68a317d14457c6b works for me locally but fails on CI, which is why I disabled that part of the test completely for now.
> disable large tree test

- openmls/src/group/public_group/validation.rs
In the log message for an invalid lifetime, include the Credential, so that the relevant leaf node can be identified.
See #1815
> Improve Lifetime log message

- openmls/src/group/mls_group/processing.rs
Small follow-up to #1846. Instead of storing the whole group state after decrypting a message, it only stores the message_secrets_store.
> perf: Avoid storing the whole group state after decryption
