openmls/openmls

Cargo.toml
src/crypto/dh.rs
src/crypto/signatures.rs
src/group.rs
src/kp.rs
src/tree.rs

- Polish debug output
- Make welcome message optional
- Use key package hash
- Use group context in HPKE
- Merge conflict
- Remove unused imports
- Bump version

Bump version

---

.travis.yml
Cargo.toml

We should add other platforms as well once we can actually support them with evercrypt.

Run CI on Mac as well

---

src/codec.rs
src/config.rs
src/errors.rs
src/extensions/capabilities_extension.rs
src/extensions/key_package_id_extension.rs
src/extensions/life_time_extension.rs
src/extensions/mod.rs
src/extensions/parent_hash_extension.rs
src/extensions/ratchet_tree_extension.rs
src/extensions/test_extensions.rs
src/group/errors.rs
src/group/mls_group/apply_commit.rs
src/group/mls_group/create_commit.rs
src/key_packages/codec.rs
src/key_packages/mod.rs
src/messages/mod.rs
src/tree/mod.rs
src/tree/node.rs
src/utils.rs
tests/test_config.rs
tests/test_key_packages.rs

This is the second part of the extension rewrite and is based on #86.
There will be another one ... This one makes extensions usable and starts tests. But extensions aren't used yet. So that has to happen first in another PR.
There are multiple ways to implement extensions. This PR takes the trait approach. Generics would be another good option.
Open To Dos
Fixes_not_yet #32
Fixes_not_yet #59

Extensions 2/?

---

src/ciphersuite/mod.rs
src/codec.rs
src/config.rs
src/extensions/key_package_id_extension.rs
src/extensions/mod.rs
src/extensions/parent_hash_extension.rs
src/group/errors.rs
src/key_packages/codec.rs
src/key_packages/mod.rs
src/tree/mod.rs
src/tree/private_tree.rs

This PR fixes the clippy warnings that were not addressed in previous PRs.

Fix clippy warnings

---

src/codec.rs
src/config.rs
src/creds.rs
src/extensions/key_package_id_extension.rs
src/extensions/mod.rs
src/extensions/test_extensions.rs
src/key_packages/mod.rs
src/key_packages/test_key_packages.rs
src/tree/mod.rs

This implements support for the key package id extension and tests for it.
This works towards #32, #101 .

key package id extensions

---

src/ciphersuite/ciphersuites.rs
src/ciphersuite/mod.rs
src/ciphersuite/test_ciphersuite.rs

This PR extends the HPKE test to also cover `hpke_open()`.

Extend HPKE test

---

README.md
benches/benchmark.rs
src/ciphersuite/test_ciphersuite.rs
src/framing/test_framing.rs
src/key_packages/test_key_packages.rs
src/tree/test_private_tree.rs
src/tree/test_secret_tree.rs
src/tree/test_treemath.rs
tests/test_framing.rs
tests/test_group.rs

This PR makes sure that all supported ciphersuites are tested in unit tests and integration tests.
Fixes #194 and #172.

Cover all ciphersuites in tests

---

.github/workflows/main.yml
fuzz/Cargo.toml
fuzz/fuzz_targets/key_package_decode.rs
fuzz/fuzz_targets/welcome_decode.rs
src/codec.rs
src/errors.rs
src/extensions/capabilities_extension.rs
src/extensions/key_package_id_extension.rs
src/extensions/life_time_extension.rs
src/extensions/parent_hash_extension.rs
src/extensions/ratchet_tree_extension.rs
src/prelude.rs

Spot fuzzing for fuzzing targets (only welcome for now as the other one is still failing).
The target on CI makes sure that we don't break the targets and gets us a little coverage for changes (this will be useful as soon as we properly start fuzzing and compiling a corpus).
cc #154

fuzzing ci target

---

Cargo.toml
src/ciphersuite/mod.rs
src/ciphersuite/test_ciphersuite.rs
src/codec.rs
src/config.rs
src/creds.rs
src/errors.rs
src/group/mls_group/mod.rs
src/group/mls_group/new_from_welcome.rs
src/key_packages/mod.rs
tests/test_framing.rs
tests/test_group.rs

A simple example of how to use logging.
This is only an example of how to do this. Please start adding logging information to new code paths. I'll file a follow up with some more logging for existing code.
The logging level is controlled by the `RUST_LOG` env variable.
cc #142

Add logging example

---

.github/workflows/coverage.yml

config file shamelessly stolen from https://github.com/franziskuskiefer/evercrypt-rust/blob/master/.github/workflows/coverage.yml

add code coverage

---

src/group/managed_group/mod.rs
src/group/mls_group/create_commit.rs
src/group/mls_group/mod.rs
src/key_packages/mod.rs
src/messages/proposals.rs
src/tree/mod.rs
tests/test_encoding.rs
tests/test_group.rs
tests/utils/mod.rs

This PR fixes open issues; 
Fixes #234. This makes `create_commit` more flexible and efficient.
Fixes #235. No new functionality, just following up on a previously discussed change.
Finally, this PR should also fix #79.

Managed Group API 2/2

---

.github/workflows/main.yml
Cargo.toml
README.md
delivery-service/ds-lib/.gitignore
delivery-service/ds-lib/Cargo.toml
delivery-service/ds-lib/Readme.md
delivery-service/ds-lib/src/lib.rs
delivery-service/ds-lib/tests/test_codec.rs
delivery-service/ds/Cargo.toml
delivery-service/ds/README.md
delivery-service/ds/src/main.rs
delivery-service/ds/src/test.rs
src/group/managed_group/mod.rs
src/prelude.rs

A proof of concept delivery service for MLS.
The corresponding CLI PoC is in #249.

MLS PoC Delivery Service

---

.github/workflows/main.yml

disable macos fuzzing

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/mls-spec-change.md

This PR introduces issue templates. This is working towards #196.

Introduce issue templates

---

Cargo.toml
README.md

This PR bumps the version to 0.3 and makes a small change to the README file.

Version 0.3

---

src/key_packages/errors.rs
src/key_packages/mod.rs

Looks like I forgot the `KeyPackageError`

rewrite KeyPackageError

---

src/key_packages/codec.rs
src/key_packages/mod.rs

also closes #93 (nothing to do)

extension verification logging

---

.github/workflows/benches.yml
.github/workflows/cli.yml
.github/workflows/ds.yml
.github/workflows/release.yml
.github/workflows/tests.yml

Fixing this issue: https://github.com/actions/checkout/issues/299

Fix CI: Forcing CI to always checkout the HEAD commit

---

src/messages/test_welcome.rs

actually check key_package_hash

---

src/ciphersuite/signable.rs
src/credentials/errors.rs
src/extensions/mod.rs
src/extensions/ratchet_tree_extension.rs
src/group/codec.rs
src/group/mls_group/mod.rs
src/key_packages/mod.rs
src/messages/codec.rs
src/messages/mod.rs
src/messages/test_pgs.rs
src/schedule/mod.rs
src/test_util/mod.rs
src/tree/hashes.rs
src/tree/kat_encryption.rs
src/tree/kat_treemath.rs
src/tree/test_treemath.rs
tests/test_interop_scenarios.rs
tls-codec-derive/tests/decode.rs
tls-codec/src/lib.rs

This PR exposes the `PublicGroupState` for a given epoch.
This is in preparation for External Commits.

Export PublicGroupState

---

.gitignore
src/ciphersuite/codec.rs
src/group/managed_group/callbacks.rs
src/group/mls_group/mod.rs
src/messages/mod.rs
src/tree/index.rs
src/utils.rs
test_macros/src/lib.rs
tests/test_managed_group.rs
tests/utils/managed_utils/default_callbacks.rs
tls-codec-derive/src/lib.rs

Fixing a couple style issues and typos.

misc cleanup

---

src/ciphersuite/mod.rs
src/framing/ciphertext.rs
src/group/mls_group/test_mls_group.rs
src/messages/tests/test_welcome.rs

This is related to #205 . It is not perfect by any means, but I was thinking it could be an starting point.
Comments welcome @raphaelrobert @franziskuskiefer

Make MAC tag length variable

---

src/error.rs

This reverts #388 commit 4e322a44594ad4b6a713d50dd4bf35efc6f1db5b.

Revert "Fix error description visibility (#388)"

---

src/tree/tests/test_treemath.rs
src/tree/treemath.rs

I ran into some infinite loops while testing because tree math didn't check that inputs are valid. I added a couple checks that should cover most cases.

check that tree math input is valid

---

cli/src/user.rs
evercrypt_backend/src/provider.rs
interop_client/src/main.rs
memory_keystore/src/lib.rs
openmls/src/group/mls_group/test_proposals.rs
openmls/src/test_utils/test_framework/mod.rs
openmls/tests/test_group.rs
openmls/tests/utils/mls_utils/mod.rs

Clippy was blocked by an error (also on the CI) which is fixed now and I also fixed several warnings.
This PR only contains the clippy suggestions.

Fixes for clippy errors and warnings

---

evercrypt_backend/src/provider.rs
openmls/src/ciphersuite/ciphersuites.rs
openmls/src/ciphersuite/mod.rs
openmls/src/config/mod.rs
rust_crypto/src/lib.rs
traits/src/types.rs

Fixes #594
Note that the cipher suite is not actually usable because no provider supports it at this point

Add MLS10_256_DHKEMP384_AES256GCM_SHA384_P384 definition

---

openmls/src/framing/codec.rs
openmls/src/framing/message.rs
openmls/src/framing/plaintext.rs
openmls/src/framing/validation.rs
openmls/src/group/managed_group/application.rs
openmls/src/group/managed_group/mod.rs
openmls/src/messages/public_group_state.rs
openmls/src/schedule/errors.rs
openmls/src/schedule/mod.rs

This PR is the same as #602, except for the functional changes.
Fixes #509.

Clippy warnings from Rust 1.57

---

openmls/src/messages/tests/test_welcome.rs

This PR fixes #600. 
(Context: the backend from the new testing template was not applied everywhere)
Blocked by #613.

Fix the bug described in #600

---

openmls/src/group/mls_group/config.rs
openmls/src/prelude.rs

This PR removes the `UpdatePolicy` stub, because it wasn't used.

Remove UpdatePolicy stub

---

openmls/src/messages/public_group_state.rs

The change was already implemented, only the comments needed to be changed.
Fixes #661.

Add protocol version to PGS

---

openmls/Cargo.toml
openmls/src/treesync/node/parent_node.rs
openmls/src/treesync/treekem.rs

This PR re-introduces parallelization for TreeKEM operations.
Fixes #108.

Re-introduce parallelization

---

openmls/src/framing/mod.rs
openmls/src/prelude.rs

Include MlsMessageIn and MlsMessageOut in prelude

---

.github/workflows/checks.yml
.github/workflows/docs.yml

This PR adds `cargo doc` checks with annotations.

Add cargo doc checks

---

cli/src/identity.rs
cli/src/main.rs
cli/src/user.rs

Upgrade CLI to use MlsGroup

---

cli/src/user.rs
delivery-service/ds-lib/src/lib.rs
delivery-service/ds/src/main.rs
delivery-service/ds/src/test.rs
openmls/src/framing/message.rs
openmls/src/group/mod.rs

Close #642
* Expose converting `MlsMessageOut` to `MlsMessageIn`
* Use `MlsMessageIn` in the DS instead of `DsMlsMessage`
* Remove `DsMlsMessage`
* Update the DS tests to use `MlsGroup` instead of `CoreGroup`

Upgrade DS to accept MlsMessageIn

---

.github/workflows/gh-pages.yml

This PR introduces a fix for the mdBook section.

Fix mdBook build/deploy

---

.github/workflows/gh-pages.yml

Add manual trigger to ghpages workflow

---

.github/workflows/gh-pages.yml

We can do the CSS styling later

Builds the documentation in one go

---

openmls/src/group/mls_group/mod.rs

#723: [Bug] Unable to get Group epoch

#723: [Bug] Unable to get Group epoch

---

openmls/src/group/core_group/proposals.rs
openmls/src/group/mod.rs
openmls/src/prelude.rs

This PR exposes `StagedCommit` and the necessary queued proposals. It also cleans up `prelude.rs` a bit.

Expose StagedCommit again

---

evercrypt_backend/Cargo.toml
memory_keystore/Cargo.toml
openmls_rust_crypto/Cargo.toml
traits/Cargo.toml

Also, add `openmls_` prefix to memory key store crate name.

set metadata for all crate

---

cli/Cargo.toml
delivery-service/ds-lib/Cargo.toml
delivery-service/ds/Cargo.toml
evercrypt_backend/Cargo.toml
interop_client/Cargo.toml
openmls/Cargo.toml
openmls_rust_crypto/Cargo.toml
traits/Cargo.toml

I released tls_codec v.0.2.0 and hpke-rs v.0.1.0 and bumped their versions here to get off the pre-releases.

tls_codec v.0.2.0, hpke-rs v.0.1.0

---

openmls/src/extensions/capabilities_extension.rs
openmls/src/extensions/external_key_id_extension.rs
openmls/src/extensions/life_time_extension.rs
openmls/src/extensions/mod.rs
openmls/src/extensions/parent_hash_extension.rs
openmls/src/extensions/ratchet_tree_extension.rs
openmls/src/extensions/required_capabilities.rs
openmls/src/group/group_context.rs

Some cleanup on rustdocs for extensions.
fixes #772

Cleaned up rustdocs for extensions

---

delivery-service/ds/src/main.rs
interop_client/src/main.rs
openmls/src/framing/plaintext.rs
openmls/src/framing/test_framing.rs
openmls/src/group/core_group/new_from_welcome.rs
openmls/src/group/core_group/past_secrets.rs
openmls/src/group/core_group/test_core_group.rs
openmls/src/group/core_group/test_duplicate_extension.rs
openmls/src/group/core_group/test_past_secrets.rs
openmls/src/group/core_group/test_proposals.rs
openmls/src/group/group_context.rs
openmls/src/group/mls_group/creation.rs
openmls/src/group/mod.rs
openmls/src/group/tests/kat_messages.rs
openmls/src/group/tests/kat_transcripts.rs
openmls/src/group/tests/test_framing_validation.rs
openmls/src/group/tests/utils.rs
openmls/src/messages/mod.rs
openmls/src/messages/tests/test_codec.rs
openmls/src/messages/tests/test_welcome.rs
openmls/src/schedule/kat_key_schedule.rs
openmls/src/test_utils/test_framework/mod.rs
openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
openmls/src/treesync/treekem.rs

I went through to find public struct members and removed the two I found.
Fixes #808

Remove public members from GroupEpoch and EncryptedGroupSecrets

---

book/src/message_validation.md
openmls/src/ciphersuite/signature.rs
openmls/src/credentials/mod.rs
openmls/src/group/tests/test_proposal_validation.rs
openmls/src/key_packages/mod.rs

As suggested by the title, this PR adds tests for ValSem100-ValSem103.
It also adds some test/test-utils only functions to facilitate the tests.

Proposal validation tests (receiver side) for ValSem100-103

---

openmls/src/group/errors.rs
openmls/src/group/mls_group/config.rs
openmls/src/group/mls_group/creation.rs
openmls/src/group/mls_group/errors.rs
openmls/src/group/mls_group/exporting.rs
openmls/src/group/mls_group/membership.rs
openmls/src/group/mls_group/mod.rs
openmls/src/group/mls_group/processing.rs
openmls/src/group/mls_group/resumption.rs
openmls/src/group/mls_group/ser.rs
openmls/src/group/mls_group/updates.rs
openmls/src/group/mod.rs
openmls/src/prelude.rs

Fix group API rustdoc

---

openmls/src/messages/mod.rs
openmls/src/messages/proposals.rs
openmls/src/messages/public_group_state.rs

Fixes #774.
Note that this PR reshuffles some code for types according to their visibility, but the code is not changed.

Fix message rustdocs

---

cli/Cargo.toml
delivery-service/ds-lib/Cargo.toml
delivery-service/ds/Cargo.toml
evercrypt_backend/Cargo.toml
interop_client/Cargo.toml
memory_keystore/Cargo.toml
openmls/Cargo.toml
openmls/fuzz/Cargo.toml
openmls_rust_crypto/Cargo.toml
traits/Cargo.toml

This PR drops the crates.io patches & bumps the version for the next pre-release.

Prepare next pre-release

---

.github/workflows/coverage.yml

This is an attempt to improve the sometimes seemingly random coverage results.

Force clean stage for tarpaulin

---

README.md
book/src/SUMMARY.md
book/src/introduction.md

This PR creates a new file for the book intro, where it imports the readme. It also adds a brief intro to the book in addition to the readme contents.

Import readme for book intro

---

book/src/SUMMARY.md
book/src/user_manual/create_key_package.md
book/src/user_manual/identity.md

Adds some general information, renames the section and adds links to the relevant OpenMLS modules.

Expanding on the credential and key package sections of the book

---

CHANGELOG.md
evercrypt_backend/Cargo.toml
memory_keystore/Cargo.toml
openmls/Cargo.toml
openmls_rust_crypto/Cargo.toml
traits/Cargo.toml

This tags the last pre-release before v0.4.
After this landed no other changes should be merged for v0.4.

final v0.4 pre-release

---

README.md
openmls/README.md

Update README with new Android targets

---

CHANGELOG.md
openmls/src/group/mls_group/exporting.rs

Not sure if this is being consumed anywhere yet

Typo in resumption_secret method

---

.github/workflows/new_issue.yml

This workflow adds all new issues to a global project board.

Add new_issue workflow

---

openmls/src/group/tests/kat_messages.rs
openmls/src/tree/tests_and_kats/kats/kat_encryption.rs

They are breaking all the time right now and don't really give us much value.
I filed #1051 for tracking this.

disable kat_messages and kat_encryption

---

openmls/src/framing/ciphertext.rs
openmls/src/framing/codec.rs
openmls/src/framing/mod.rs
openmls/src/framing/plaintext.rs
openmls/src/framing/test_framing.rs
openmls/src/framing/validation.rs
openmls/src/group/core_group/process.rs
openmls/src/group/core_group/proposals.rs
openmls/src/group/core_group/staged_commit.rs
openmls/src/group/core_group/test_core_group.rs
openmls/src/group/core_group/test_external_init.rs
openmls/src/group/tests/kat_messages.rs
openmls/src/group/tests/test_commit_validation.rs
openmls/src/group/tests/test_external_commit_validation.rs
openmls/src/group/tests/test_framing_validation.rs
openmls/src/group/tests/test_group.rs
openmls/src/group/tests/test_proposal_validation.rs
openmls/src/messages/mod.rs
openmls/src/messages/proposals.rs
openmls/src/tree/secret_tree.rs

Please see the commit messages for a description.
I am working towards solving #979 on branch `duesee/spec_issue_979` and figured that I can extract PR-able commits to slowly make some progress on `main`.

Work towards solving #979.

---

openmls/src/framing/message.rs
openmls/src/framing/test_framing.rs

Cleaning up nits that were missed.

Follow up on #902 & #1055

---

book/src/message_validation.md
openmls/src/framing/ciphertext.rs
openmls/src/framing/codec.rs
openmls/src/framing/plaintext.rs
openmls/src/group/tests/test_framing.rs

Sync: Align the padding mechanism with draft-ietf-mls-protocol-16.

---

openmls/src/extensions/application_id_extension.rs
openmls/src/extensions/capabilities_extension.rs
openmls/src/extensions/codec.rs
openmls/src/extensions/mod.rs
openmls/src/extensions/test_extensions.rs
openmls/src/group/core_group/test_proposals.rs
openmls/src/key_packages/mod.rs
openmls/src/key_packages/test_key_packages.rs
openmls/tests/test_key_packages.rs

refactor: Rename `external_key_id` to `application_id`.

---

openmls/src/extensions/codec.rs
openmls/src/extensions/external_pub_extension.rs
openmls/src/extensions/external_sender_extension.rs
openmls/src/extensions/mod.rs
openmls/src/extensions/test_extensions.rs
openmls/src/group/tests/test_encoding.rs
openmls/src/group/tests/test_group.rs
openmls/src/group/tests/utils.rs
openmls/src/key_packages/mod.rs
openmls/src/key_packages/test_key_packages.rs
openmls/src/test_utils/test_framework/client.rs
openmls/tests/book_code.rs

This PR introduces the `external_pub` extension needed to make progress on #719 and #1027. This is basically the (unchanged) start of closed #1106.

Use GroupInfo instead of PublicGroupState. (1/2)

---

openmls/src/binary_tree/array_representation/diff.rs
openmls/src/binary_tree/array_representation/mod.rs
openmls/src/binary_tree/array_representation/treemath.rs
openmls/src/group/tests/test_remove_operation.rs
openmls/src/treesync/diff.rs
openmls/src/treesync/node.rs
openmls/src/treesync/node/parent_node.rs
openmls/src/treesync/treekem.rs

Fixes #875.
Another preparatory PR for the full tree implementation.

Filtered direct path

---

openmls/src/messages/mod.rs

fix: Remove `Verifiable` implementation of `GroupInfo`.

---

openmls/src/group/tests/test_proposal_validation.rs
openmls/src/treesync/node/leaf_node.rs

Fixes #1226.
This also fixes a bug in LeafNode.update_and_re_sign when updating with a leaf node.

re-enable valsem110 test

---

cli/src/backend.rs
cli/src/main.rs
cli/src/networking.rs
cli/src/user.rs
delivery-service/ds/src/main.rs
delivery-service/ds/src/test.rs
openmls/src/binary_tree/array_representation/kat_treemath.rs
openmls/src/ciphersuite/hash_ref.rs
openmls/src/credentials/codec.rs
openmls/src/error.rs
openmls/src/extensions/mod.rs
openmls/src/extensions/test_extensions.rs
openmls/src/framing/mls_content.rs
openmls/src/group/core_group/new_from_external_init.rs
openmls/src/group/tests/test_commit_validation.rs
openmls/src/group/tests/test_encoding.rs
openmls/src/group/tests/test_framing.rs
openmls/src/group/tests/test_group.rs
openmls/src/group/tests/tree_printing.rs
openmls/src/group/tests/utils.rs
openmls/src/messages/codec.rs
openmls/src/messages/tests/test_welcome.rs
openmls/src/schedule/kat_key_schedule.rs
openmls/src/test_utils/mod.rs
openmls/src/test_utils/test_framework/mod.rs
openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
openmls/tests/test_decryption_key_index.rs
openmls/tests/test_interop_scenarios.rs
openmls/tests/test_mls_group.rs
traits/src/types.rs

Mostly related to string format!().
Makes the CI happy on all other branches :)

chore: autofix new clippy lints from 1.67

---

.github/workflows/benches.yml
.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/cli.yml
.github/workflows/clippy.yml
.github/workflows/docs.yml
.github/workflows/ds.yml
.github/workflows/fuzz.yml
.github/workflows/tests.yml

CI isn't running when doing PRs not against main. This PR changes the CI to always run on PRs.

enable workflows for all PRs

---

openmls/src/ciphersuite/hpke.rs
openmls/src/ciphersuite/mod.rs
openmls/src/ciphersuite/signature.rs
openmls/src/ciphersuite/tests/test_ciphersuite.rs
openmls/src/group/core_group/new_from_welcome.rs
openmls/src/group/core_group/test_core_group.rs
openmls/src/group/public_group/diff/process_path.rs
openmls/src/group/tests/test_commit_validation.rs
openmls/src/messages/mod.rs
openmls/src/messages/tests/test_welcome.rs
openmls/src/treesync/node/encryption_keys.rs
openmls/src/treesync/node/parent_node.rs
openmls/src/treesync/treekem.rs

This PR closes #1258 by implementing the labeled HPKE encryption.
It also fixes the signature label.

hpke encrypt with label

---

openmls/src/treesync/node.rs
openmls/src/treesync/node/codec.rs

chore: Derive `tls_codec` for `Node`.

---

openmls/src/credentials/tests.rs
openmls/src/versions.rs

`ProtocolVersion` is two bytes now.

update protocol version to u16

---

openmls/src/binary_tree/array_representation/treemath.rs
openmls/src/ciphersuite/secret.rs
openmls/src/group/core_group/new_from_welcome.rs
openmls/src/tree/secret_tree.rs
openmls/src/tree/sender_ratchet.rs
openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
openmls/src/tree/tests_and_kats/kats/secret_tree.rs
openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs

adding secret tree to the interop branch

kat secret tree

---

openmls/src/schedule/kat_psk_secret.rs
openmls/src/schedule/mod.rs
openmls/src/schedule/psk.rs
openmls/test_vectors/psk_secret.json

Adds the PSK secret test vector and the code to pass it.

PSK secret KAT

---

README.md

Removes the draft version since it no longer makes sense.

Remove draft version

---

openmls/src/group/core_group/mod.rs
openmls/src/group/public_group/builder.rs
openmls/src/group/public_group/mod.rs

This is the final PR that makes interop (modulo some unsupported features) work.

Make interop work.

---

openmls_rust_crypto/Cargo.toml
openmls_rust_crypto/src/provider.rs

Upgrade P256

---

openmls/src/group/mls_group/updates.rs

internal function name, so no compatibility issues

fix typo in function name (udpate -> update)

---

cli/src/user.rs
openmls/src/group/core_group/new_from_welcome.rs
openmls/src/group/core_group/proposals.rs
openmls/src/group/core_group/staged_commit.rs
openmls/src/group/tests/external_remove_proposal.rs
openmls/src/group/tests/test_framing.rs
openmls/src/test_utils/test_framework/mod.rs
openmls/src/treesync/diff.rs
openmls/src/utils.rs

New Rust version, new adventures.

Fix let/else formatting & clippy warnings

---

cli/src/user.rs

When removing a group, also remove it from the group_list !

fix: also remove group from group_list

---

cli/src/conversation.rs
cli/src/main.rs
cli/src/user.rs

Handle message sender information to display the sender while receiving messages.

feat[sender info]: add message sender information in conversation

---

openmls/src/group/mls_group/config.rs

Add ability to set RequiredCapabilities in MlsGroupConfig builder

---

openmls/src/extensions/codec.rs
openmls/src/extensions/last_resort.rs
openmls/src/extensions/mod.rs
openmls/src/extensions/test_extensions.rs
openmls/src/group/mls_group/config.rs
openmls/src/group/mls_group/creation.rs
openmls/src/key_packages/mod.rs

Add support for the last resort extension specified in the mls-extensions draft. I've set the extension ID for last resort extension to 10 as per https://github.com/mlswg/mls-extensions/pull/23.

Last resort extension

---

openmls/src/kat_vl.rs
openmls/src/lib.rs
openmls/test_vectors/deserialization.json

This PR implements the KAT from https://github.com/mlswg/mls-implementations/pull/174.

Add vector deserialization KAT

---

openmls/src/treesync/diff.rs
openmls/src/treesync/mod.rs

Hey, I stumbled upon those small improvements while using the lib, I guess they deserve to be merged upstream 😄

perf: small perf improvements

---

openmls/src/group/core_group/kat_passive_client.rs

See https://github.com/mlswg/mls-implementations/issues/181 and #1529

Disable failing passive client tests

---

openmls/src/framing/codec.rs
openmls/src/framing/message_out.rs
openmls/src/framing/public_message.rs
openmls/src/group/mls_group/mod.rs
openmls/src/key_packages/mod.rs
openmls/src/key_packages/test_key_packages.rs
openmls/src/messages/group_info.rs

This PR makes a few small changes/additions to the public API of OpenMLS.

Small API improvements

---

openmls/src/group/core_group/staged_commit.rs
openmls/src/group/public_group/staged_commit.rs

At the moment, `update_path_leaf_node` always returns `None` for the public group variant of staged commit states. It doesn't have to, though. This PR adds the update path leaf node to the relevant structs s.t. the function can return a useful result even in the public group case.

Return leaf node for public staged commit states

---

openmls/src/extensions/required_capabilities.rs
openmls/src/group/core_group/mod.rs
openmls/src/group/mls_group/proposal.rs
openmls/src/group/mls_group/test_mls_group.rs
openmls/src/messages/proposals.rs
openmls/tests/test_mls_group.rs

Make propose_group_context_extensions not `test` only and add an integration test.
fixes #1549

expose propose_group_context_extensions and add a function

---

.github/workflows/interop.yml

This reverts commit 7e111858904812f42f6fef922803c3a64891328a.

Revert "Disable MLS++ interop on CI (#1555)"

---

openmls/benches/benchmark.rs

After #1573 got merged we can have ml-kem benchmarks.
Replacing #1561

benchmarks for ml-kem

---

openmls/src/key_packages/mod.rs
openmls/src/messages/tests/test_welcome.rs
traits/src/storage.rs

A small update to storage docs and a follow up to #1565.

Storage docs and small fix

---

openmls/tests/test_mls_group.rs
openmls_test/src/lib.rs

Check that gce propsals are available in the staged commit.
As a drive-by this also adds logging to all tests in the test macro.

Update gce staged commit test

---

openmls/src/group/core_group/mod.rs
openmls/src/group/core_group/new_from_welcome.rs
openmls/src/group/mls_group/creation.rs
openmls/src/group/mls_group/mod.rs
openmls/src/messages/group_info.rs
openmls/src/messages/tests/test_welcome.rs

API for processed welcome

---

.github/workflows/interop.yml

Another interop fix

---

memory_storage/src/lib.rs
memory_storage/src/test_store.rs
openmls/src/group/mls_group/processing.rs
traits/src/storage.rs

@kkohbrok noticed that we have a duplicate method in our Storage trait. This PR removes one of them.

Remove Duplicate Method in Storage trait

---

openmls/src/group/mls_group/test_mls_group.rs
openmls/src/group/mls_group/updates.rs

Just two tests to explicitly test what was broken before.
cc #1567 #1599 #1606

more update proposal tests

---

Cargo.toml
basic_credential/Cargo.toml
libcrux_crypto/Cargo.toml
memory_storage/Cargo.toml
openmls/Cargo.toml
openmls_rust_crypto/Cargo.toml
traits/Cargo.toml

We don't need the features of the prerelease.

Downgrade tls_codec to 0.4.1

---

openmls_test/Cargo.toml

Another round of fixes for the v0.6 release.

Set versions for openmls_test

---

CHANGELOG.md
openmls/src/group/core_group/process.rs
openmls/src/group/core_group/proposals.rs
openmls/src/group/core_group/staged_commit.rs
openmls/src/group/mls_group/membership.rs
openmls/src/group/mls_group/mod.rs
openmls/src/group/mls_group/proposal.rs
openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
openmls/src/group/public_group/mod.rs
openmls/src/group/public_group/staged_commit.rs
openmls/src/group/public_group/tests.rs
openmls/tests/book_code.rs
traits/src/public_storage.rs

This PR makes the handling of queued proposals more consistent across the different group types. Proposals were not always saved in the storage provider and were not always cleared after successfully merging a Commit.

Consistent handling of queued proposals.

---

CHANGELOG.md
basic_credential/Cargo.toml
libcrux_crypto/Cargo.toml
memory_storage/Cargo.toml
openmls/Cargo.toml
openmls_rust_crypto/Cargo.toml
openmls_test/Cargo.toml
traits/Cargo.toml

Bump crate versions for v0.6

---

openmls/src/group/mls_group/processing.rs
openmls/src/group/public_group/process.rs
openmls/src/group/public_group/staged_commit.rs
openmls/src/group/public_group/validation.rs
openmls/src/key_packages/key_package_in.rs
openmls/src/messages/proposals.rs
openmls/src/treesync/diff.rs
openmls/src/treesync/node/leaf_node.rs
openmls/src/treesync/treekem.rs

This PR adds a lot of annotations for validation checks, as well as a few smaller missing validation checks.

Validation Progress

---

CHANGELOG.md
openmls/src/messages/group_info.rs

`VerifiableGroupInfo::epoch()` added to public API

---

CHANGELOG.md
openmls/src/framing/validation.rs
openmls/src/group/errors.rs
openmls/tests/own_messages.rs

This PR improves the error retruned when attempting to process own private messages.

Feat: Better error when attempting to decrypt own messages

---

.github/workflows/coverage.yml

ci: Fix coverage

---

cli/src/conversation.rs
cli/src/user.rs
libcrux_crypto/src/crypto.rs
memory_storage/src/persistence.rs
openmls/src/binary_tree/array_representation/diff.rs
openmls/src/framing/public_message.rs
openmls/src/group/mls_group/commit_builder.rs
openmls/src/group/mls_group/create_commit.rs
openmls/src/group/mls_group/proposal_store.rs
openmls/src/group/public_group/diff/apply_proposals.rs
openmls/src/group/public_group/diff/compute_path.rs
openmls/src/test_utils/frankenstein/framing.rs
openmls/src/treesync/diff.rs
openmls/src/treesync/treekem.rs
traits/src/storage.rs

Clippy has a few new complaints. This PR fixes them.

Clippy fixes

---

CHANGELOG.md
openmls/src/group/mls_group/proposal_store.rs
openmls/src/group/mls_group/tests_and_kats/tests/proposals.rs

Fixes the issue and adds a test to verify the fix.

fix: clear update proposals when a remove proposal is present for a given leaf

---

.github/workflows/gh-pages.yml

add cname to gh-pages action

---

openmls-wasm/src/lib.rs

Adds a simple wasm binding for `MlsGroup.create_message()` and a corresponding test.

feat(wasm): add binding for MlsGroup.create_message()

---

openmls-wasm/check-size.sh

bump wasm threshold to 1.7MiB

---

openmls/src/binary_tree/array_representation/mod.rs
openmls/src/ciphersuite/mod.rs
openmls/src/credentials/mod.rs
openmls/src/extensions/mod.rs
openmls/src/framing/mod.rs
openmls/src/key_packages/mod.rs
openmls/src/messages/mod.rs
openmls/src/schedule/mod.rs

Polishes the module documentation. Replaces #1722.

doc: Improve the module documentation

---

CHANGELOG.md

doc: Add external add proposal to changelog

---

openmls/src/group/tests_and_kats/tests/external_join_add_proposal.rs

Add validation test for valn1504

---

openmls/src/group/public_group/diff/apply_proposals.rs
openmls/src/treesync/diff.rs
openmls/tests/mls_group.rs

Fixes #1794 
Checkout 2bef38c396bc8b6ef704677e4f568bf504f374c0 to see that the test is failing on current main.

fix: trim diff tree after processing all proposals

---

Cargo.toml
basic_credential/Cargo.toml
libcrux_crypto/Cargo.toml
memory_storage/Cargo.toml
openmls/Cargo.toml
openmls_rust_crypto/Cargo.toml
openmls_test/Cargo.toml
sqlite_storage/Cargo.toml
traits/Cargo.toml

Bump packages to full (non-pre) versions

---

openmls/src/group/mls_group/commit_builder/external_commits.rs
openmls/src/group/mls_group/mod.rs
openmls/src/group/tests_and_kats/tests/external_commit_builder.rs

fix: external commit builder regression
